import test from 'node:test';
import assert from 'node:assert/strict';
import {apply,seed,emptyState,risk,today,dateOffset,total,projectCost} from '../lib/crm.ts';
import type {State,Command} from '../lib/crm.ts';
function fixture(){let s=emptyState();const save=(kind:string,record:unknown)=>s=apply(s,{action:'save',kind,record} as Command);save('companies',{id:'c',demo:false,name:'Cliente',contact:'',email:'',phone:'',contactDays:30});save('opportunities',{id:'o',demo:false,companyId:'c',title:'Servicio',amount:1000,stage:'Cualificación',closeDate:dateOffset(5),nextStep:'',nextDate:'',createdAt:today()});save('quotes',{id:'q',demo:false,opportunityId:'o',title:'Oferta',lines:[{description:'Fijo',quantity:1,price:1000,policy:'fixed',tasks:'Preparar\nEntregar'},{description:'Por horas',quantity:10,price:90,policy:'hours',tasks:'Soporte'},{description:'Por hitos',quantity:1,price:600,policy:'milestones',tasks:'Hito'}]});return apply(s,{action:'confirm',id:'q'})}
const inv=(s:State,policy:string,rest:Partial<Command>={})=>apply(s,{action:'invoice',id:s.orders[0].id,policy,title:crypto.randomUUID(),date:today(),dueDate:dateOffset(30),...rest});
test('full lifecycle and completed task retained',()=>{let s=fixture();assert.equal(s.projects.length,1);assert.equal(s.delivery.length,4);assert.equal(s.opportunities[0].stage,'Ganada');s=apply(s,{action:'save',kind:'hours',record:{id:'h',taskId:s.delivery[0].id,date:today(),hours:1,cost:35,notes:'Entrega'}});assert.equal(total(s.orders[0].lines)-projectCost(s,s.projects[0].id),2465);s=inv(s,'fixed');assert.equal(s.invoices[0].amount,1000);s=apply(s,{action:'pay',id:s.invoices[0].id,date:today()});assert.equal(s.invoices[0].paid,true);assert.equal(s.payments[0].amount,1000);s=apply(s,{action:'save',kind:'followups',record:{id:'f',opportunityId:'o',title:'Llamar',dueDate:today(),done:false}});s=apply(s,{action:'complete',id:'f'});assert.equal(s.followups.length,1);assert.equal(s.followups[0].done,true);assert.throws(()=>apply(s,{action:'pay',id:s.invoices[0].id,date:today()}),/ya está cobrada/)});
test('hour invoices use selling rate, not cost, and cannot bill twice',()=>{let s=fixture();const task=s.delivery.find(t=>t.lineIndex===1)!;s=apply(s,{action:'save',kind:'hours',record:{id:'h',taskId:task.id,date:today(),hours:2.5,cost:35,notes:'Soporte'}});s=inv(s,'hours',{hourIds:['h']});assert.equal(s.invoices[0].amount,225);assert.equal(projectCost(s,s.projects[0].id),87.5);assert.throws(()=>inv(s,'hours',{hourIds:['h']}),/ya facturadas/);assert.throws(()=>apply(s,{action:'delete',kind:'hours',id:'h'}),/ya están facturadas/);s=apply(s,{action:'delete',kind:'invoices',id:s.invoices[0].id});assert.equal(inv(s,'hours',{hourIds:['h']}).invoices[0].amount,225)});
test('milestones cannot exceed remaining order amount',()=>{let s=fixture();s=inv(s,'milestones',{amount:250});assert.throws(()=>inv(s,'milestones',{amount:351}),/pendiente/);s=inv(s,'milestones',{amount:350});assert.equal(s.invoices.reduce((a,i)=>a+i.amount,0),600);assert.throws(()=>inv(s,'milestones',{amount:1}),/pendiente/)});
test('fixed policy cannot invoice twice or bill hours for wrong line',()=>{let s=fixture();s=inv(s,'fixed');assert.throws(()=>inv(s,'fixed'),/pendiente/);s=apply(s,{action:'save',kind:'hours',record:{id:'h',taskId:s.delivery[0].id,date:today(),hours:1,cost:35,notes:''}});assert.throws(()=>inv(s,'hours',{hourIds:['h']}),/no corresponden/)});
test('risk boundaries, completed followups, won opportunities and reasons',()=>{let s=fixture();const o=s.opportunities[0];o.stage='Cualificación';assert.equal(risk(s,o).level,1);o.closeDate=dateOffset(8);assert.equal(risk(s,o).level,0);o.nextDate=dateOffset(-1);assert.match(risk(s,o).reason,/vencido/);o.nextDate='';o.createdAt=dateOffset(-30);assert.match(risk(s,o).reason,/30 días/);s.companies[0].contactDays=90;assert.equal(risk(s,o).level,0);o.createdAt=today();o.stage='Ganada';o.closeDate=dateOffset(-5);assert.equal(risk(s,o).level,0);o.stage='Cualificación';s.followups.push({id:'f',demo:false,opportunityId:o.id,title:'Llamar',dueDate:dateOffset(-1),done:false});assert.equal(risk(s,o).level,2);s.followups[0].done=true;assert.equal(risk(s,o).level,1)});
test('undo detects intervening changes and dependencies prevent deletion',()=>{let s=fixture();s=apply(s,{action:'stage',id:'o',stage:'Propuesta',expectedStage:'Ganada'});s=apply(s,{action:'stage',id:'o',stage:'Ganada',expectedStage:'Propuesta'});assert.equal(s.opportunities[0].stage,'Ganada');assert.throws(()=>apply(s,{action:'stage',id:'o',stage:'Cualificación',expectedStage:'Propuesta'}),/ha cambiado/);assert.throws(()=>apply(s,{action:'delete',kind:'companies',id:'c'}),/vinculados/);assert.throws(()=>apply(s,{action:'confirm',id:'q'}),/ya está confirmado/)});
test('legacy stages fold into the short pipeline and a lead converts once',()=>{let s=fixture();(s.opportunities[0] as {stage:string}).stage='Proposal sent & Negotiation';s=apply(s,{action:'stage',id:'o',stage:'Negociación',expectedStage:'Propuesta'});assert.equal(s.opportunities[0].stage,'Negociación');s=apply(s,{action:'save',kind:'leads',record:{id:'lead',name:'Clínica Bruma',contact:'Elena',email:'elena@bruma.example',phone:'',source:'Evento',status:'Cualificado',notes:'Quiere una propuesta.',nextDate:dateOffset(2),createdAt:today()}});s=apply(s,{action:'convertLead',id:'lead'});const lead=s.leads.find(l=>l.id==='lead')!;assert.equal(lead.status,'Convertido');assert.equal(s.companies.some(c=>c.id===lead.convertedCompanyId&&c.name==='Clínica Bruma'),true);assert.equal(s.opportunities.find(o=>o.id===lead.convertedOpportunityId)?.stage,'Cualificación');assert.match(s.interactions.at(-1)?.notes||'',/Lead convertido/);assert.throws(()=>apply(s,{action:'convertLead',id:'lead'}),/ya está convertido/);s.leads.push({id:'discarded',demo:false,name:'Descartado',contact:'',email:'',phone:'',source:'Otro',status:'Descartado',notes:'',nextDate:'',createdAt:today()});assert.throws(()=>apply(s,{action:'convertLead',id:'discarded'}),/descartado/)});
test('delete demo is scoped, atomic, and retains real data',()=>{let s=seed();s=apply(s,{action:'save',kind:'companies',record:{id:'real',name:'Real',contact:'',email:'',phone:'',contactDays:30}});const clean=apply(s,{action:'deleteDemo'});assert.deepEqual(clean.companies.map(c=>c.id),['real']);assert.equal(clean.invoices.length,0);assert.equal(clean.projects.length,0);s=apply(s,{action:'save',kind:'interactions',record:{id:'real-contact',companyId:'demo-company',opportunityId:'',kind:'Nota',date:today(),notes:'No perder'}});assert.equal(s.interactions.at(-1)?.demo,true);s.interactions.at(-1)!.demo=false;assert.throws(()=>apply(s,{action:'deleteDemo'}),/datos propios/);assert.equal(s.interactions.length,4)});
test('validation keeps original state and rejects invalid references and dates',()=>{const s=fixture();const json=JSON.stringify(s);assert.throws(()=>apply(s,{action:'save',kind:'hours',record:{id:'bad',taskId:'other-tenant',date:today(),hours:1,cost:10,notes:''}}),/no existe/);assert.equal(JSON.stringify(s),json);assert.throws(()=>inv(s,'fixed',{date:'2026-02-30'}),/Fecha no válida/);assert.throws(()=>inv(s,'fixed',{dueDate:dateOffset(-1)}),/anterior/)});
test('deleting invoice removes payment and frees invoiceable amount',()=>{let s=inv(fixture(),'fixed');s=apply(s,{action:'pay',id:s.invoices[0].id,date:today()});s=apply(s,{action:'delete',kind:'invoices',id:s.invoices[0].id});assert.equal(s.payments.length,0);assert.equal(inv(s,'fixed').invoices[0].amount,1000)});
