'use client';
import { useEffect,useRef,useState, type ReactNode } from 'react';
import { Crosshair,Columns3,Building2,FileText,FolderKanban,Receipt,Inbox,Search,Plus,ArrowUpRight,ArrowRight,Download,Clock3,ChevronRight,Trash2,Pencil,Users,LogOut,RefreshCw,X,Bot,UserPlus,UserMinus } from 'lucide-react';
import { FocusQueue } from './focus-queue';
import { pipelineNextAction, pipelineOpportunities, isOpenOpportunity, followupDraft } from '@/lib/pipeline';
import { Board } from './board';
import { Roadmap } from './roadmap';
import { HermesPanel,hermesBrief } from './hermes-panel';
import { matchesText,projectTasks } from '@/lib/project-tasks';
import { Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription,SheetClose } from '@/components/ui/sheet';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogClose } from '@/components/ui/dialog';
import { AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel } from '@/components/ui/alert-dialog';
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from '@/components/ui/select';
import { Table,TableHeader,TableBody,TableHead,TableRow,TableCell } from '@/components/ui/table';
import { Checkbox } from '@/components/ui/checkbox';
import { Skeleton } from '@/components/ui/skeleton';
import { Empty,EmptyHeader,EmptyTitle,EmptyDescription } from '@/components/ui/empty';
import { Toaster } from '@/components/ui/sonner';
import { toast } from 'sonner';
import { stages,today,dateOffset,days,eur,total,risk,projectCost,companyForOrder,leadSources,leadStatuses,taskStatuses, type State,type Kind,type Command } from '@/lib/crm';
type Data={state:State;revision:number;tenant:string;role:string;user:string;onboarding?:boolean};
type Form={kind:Kind|'invoice'|'editInvoice'|'pay';record:any};
const nav=[{name:'Foco',icon:Crosshair},{name:'Leads',icon:Inbox},{name:'Pipeline',icon:Columns3},{name:'Empresas',icon:Building2},{name:'Ventas',icon:FileText},{name:'Proyectos',icon:FolderKanban},{name:'Facturas',icon:Receipt}];
const moduleDescriptions:Record<string,string>={Foco:'Revisa los seguimientos que necesitan atención.',Leads:'Trabaja nuevos contactos y detecta oportunidades.',Pipeline:'Avanza cada oportunidad hasta el cierre.',Empresas:'Consulta contactos e historial de tus clientes.',Ventas:'Prepara presupuestos y confirma pedidos.',Proyectos:'Organiza tareas, responsables y fechas.',Facturas:'Controla los importes pendientes y los cobros.'};
const labels:Record<string,string>={leads:'lead',companies:'empresa',opportunities:'oportunidad',interactions:'interacción',followups:'tarea de seguimiento',quotes:'presupuesto',orders:'pedido',projects:'proyecto',delivery:'tarea',hours:'parte de horas',invoice:'factura',editInvoice:'factura',pay:'cobro'};
const policyLabel:Record<string,string>={fixed:'Precio fijo',milestones:'Hitos',hours:'Horas'};
const pageCopy:Record<string,{title:string;text:string}>={
 Inicio:{title:'Tu espacio de trabajo',text:'Elige un módulo para empezar.'},
 Foco:{title:'Foco',text:'Lo que necesita una acción ahora.'},
 Leads:{title:'Leads',text:'Contactos que aún no son oportunidad.'},
 Pipeline:{title:'Pipeline',text:'Arrastra una oportunidad o pulsa Mover para cambiarla de etapa.'},
 Empresas:{title:'Empresas',text:'Clientes, contactos y cada cuánto retomar la conversación.'},
 Ventas:{title:'Ventas',text:'Presupuestos y pedidos.'},
 Proyectos:{title:'Proyectos',text:'Tareas, responsables y fechas de cada proyecto.'},
 Facturas:{title:'Facturas',text:'Lo pendiente de cobro y lo cobrado.'},
};
const feminine=new Set(['companies','opportunities','interactions','followups','delivery','invoice','editInvoice']);
const createKind=(view:string):Form['kind']=>view==='Empresas'?'companies':view==='Ventas'?'quotes':view==='Facturas'?'invoice':view==='Proyectos'?'hours':(view==='Pipeline'||view==='Foco')?'opportunities':'leads';
const createLabel:Record<string,string>={companies:'Nueva empresa',quotes:'Nuevo presupuesto',invoice:'Generar factura',hours:'Imputar horas',opportunities:'Nueva oportunidad',leads:'Nuevo lead'};
function Pick({value,onChange,options,label,disabled=false}:{disabled?:boolean;value:string;onChange:(v:string)=>void;options:(string|{value:string;label:string})[];label:string}){return <Select disabled={disabled} value={value||'__empty'} onValueChange={v=>onChange(v==='__empty'?'':v)}><SelectTrigger aria-label={label} className="picker"><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{options.map(o=>{const v=typeof o==='string'?o:o.value;return <SelectItem key={v||'empty'} value={v||'__empty'}>{typeof o==='string'?o:o.label}</SelectItem>})}</SelectContent></Select>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
function Blank({filtered=false,text='Crea el primer registro para empezar.'}:{filtered?:boolean;text?:string}){return <Empty className="empty"><EmptyHeader><EmptyTitle>{filtered?'Sin resultados':'Todavía no hay registros'}</EmptyTitle><EmptyDescription>{filtered?'Prueba otro término o cambia los filtros.':text}</EmptyDescription></EmptyHeader></Empty>}
function Badge({level,children}:{level:number;children:ReactNode}){return <span className={'badge risk-'+level}><span className="status-dot"/>{children}</span>}
function plainStatus(level:number){return level===2?'Hay que actuar':level===1?'Revisar pronto':'En orden'}
function isStage(value:string): value is (typeof stages)[number]{return (stages as readonly string[]).includes(value)}
function shortDate(value:string){return new Intl.DateTimeFormat('es-ES',{day:'numeric',month:'short',timeZone:'UTC'}).format(new Date(value+'T12:00:00Z'))}
function taskTone(task:State['delivery'][number]){return task.done?'done':task.dueDate&&task.dueDate<today()?'late':'open'}
function DueChip({task}:{task:State['delivery'][number]}){const tone=taskTone(task);return <span className={'badge'+(tone==='open'&&!task.dueDate?'':' tone-'+tone)}><span className="status-dot"/>{tone==='done'?'Hecha':!task.dueDate?'Sin fecha':(tone==='late'?'Vencida · ':'')+shortDate(task.dueDate)}</span>}
export default function CRM(){
 const [data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [view,setView]=useState('Inicio'),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[companyFilter,setCompanyFilter]=useState('all'),[projectFocus,setProjectFocus]=useState<string|null>(null),[projectLens,setProjectLens]=useState<'board'|'roadmap'>('board');
 const [selected,setSelected]=useState<{companyId:string;opportunityId?:string}|null>(null),[form,setForm]=useState<Form|null>(null),[formError,setFormError]=useState('');
 const [deletion,setDeletion]=useState<Command|null>(null);
 const [team,setTeam]=useState(false),[invite,setInvite]=useState(''),[draft,setDraft]=useState<string|null>(null),[hermesOpen,setHermesOpen]=useState(false);
 const saving=useRef(false);
 const nextActionRef=useRef<HTMLElement|null>(null),detailReturnFocus=useRef<HTMLElement|null>(null);
 function openOpportunity(opportunity:State['opportunities'][number]){detailReturnFocus.current=document.activeElement instanceof HTMLElement?document.activeElement:null;setSelected({companyId:opportunity.companyId,opportunityId:opportunity.id})}
 const formReturnFocus=useRef<HTMLElement|null>(null),hermesTrigger=useRef<HTMLButtonElement|null>(null);
 const [org,setOrg]=useState('Mi empresa'),[join,setJoin]=useState('');
 async function load(){setLoading(true);try{const r=await fetch('/api/crm',{cache:'no-store'});const d=await r.json() as any;if(!r.ok)throw new Error(d.error);setData(d);setError('')}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const agent=useRef<{data:Data|null;send:(command:Command)=>Promise<false|{state?:State}>}>({data:null,send:async()=>false});
 useEffect(()=>{const context=(document as {modelContext?:{registerTool?:(tool:object,options:{signal:AbortSignal})=>Promise<unknown>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const signal=lifecycle.signal;const register=(tool:object)=>void Promise.resolve(context.registerTool!(tool,{signal})).catch(()=>{});register({name:'navigate_siarem',description:'Abre una pantalla del CRM. No modifica registros.',inputSchema:{type:'object',properties:{view:{type:'string',enum:['Inicio',...nav.map(n=>n.name)]}},required:['view'],additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:{view?:string})=>{if(!input.view||!['Inicio',...nav.map(n=>n.name)].includes(input.view))throw new Error('Pantalla no válida');setView(input.view);setQuery('');setFilter('all');return {view:input.view}}});register({name:'list_siarem_pipeline',description:'Lista las oportunidades del tablero: empresa, importe y columna.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>{const state=agent.current.data?.state;if(!state)throw new Error('El espacio todavía no está cargado');return state.opportunities.map(item=>({id:item.id,title:item.title,stage:item.stage,amount:item.amount,company:state.companies.find(company=>company.id===item.companyId)?.name??''}))}});register({name:'move_siarem_opportunity',description:'Mueve una oportunidad a otra columna. Es la misma acción que arrastrar la tarjeta.',inputSchema:{type:'object',properties:{id:{type:'string'},stage:{type:'string',enum:[...stages]}},required:['id','stage'],additionalProperties:false},execute:async(input:{id?:string;stage?:string})=>{const state=agent.current.data?.state;const current=state?.opportunities.find(item=>item.id===input.id);if(!current||!input.stage||!isStage(input.stage))throw new Error('No encuentro esa oportunidad o la columna no existe');const saved=await agent.current.send({action:'stage',id:current.id,stage:input.stage,expectedStage:current.stage});if(!saved)throw new Error('No se pudo mover');return {id:current.id,from:current.stage,stage:input.stage}}});return()=>lifecycle.abort()},[]);
 async function send(command:Command|any){if(saving.current)return false;saving.current=true;setBusy(true);try{const r=await fetch('/api/crm',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...command,revision:data?.revision})});const d=await r.json() as any;if(!r.ok)throw new Error(d.error);if(d.token)setInvite(d.token);else setData(d);setError('');return d}catch(e){const msg=(e as Error).message;setFormError(msg);setError(msg);toast.error(msg);return false}finally{saving.current=false;setBusy(false)}}
 agent.current={data,send};
 function open(kind:Form['kind'],record:any={}){formReturnFocus.current=document.activeElement instanceof HTMLElement?document.activeElement:null;setFormError('');const defaults:Record<string,any>={leads:{name:'',contact:'',email:'',phone:'',source:'Referencia',status:'Nuevo',notes:'',nextDate:dateOffset(7),createdAt:today()},companies:{name:'',contact:'',email:'',phone:'',contactDays:30},opportunities:{companyId:selected?.companyId||data?.state.companies[0]?.id||'',title:'',amount:0,stage:stages[0],closeDate:dateOffset(14),nextStep:'',nextDate:'',createdAt:today()},interactions:{companyId:selected?.companyId,opportunityId:selected?.opportunityId||'',kind:'Llamada',date:today(),notes:''},followups:{opportunityId:selected?.opportunityId,title:'',dueDate:today(),done:false},quotes:{opportunityId:selected?.opportunityId||data?.state.opportunities[0]?.id||'',title:'',lines:[{description:'',quantity:1,price:0,policy:'fixed',tasks:'Preparación\nEjecución\nEntrega y revisión'}]},projects:{title:'',body:'',orderId:''},delivery:{projectId:'',lineIndex:0,title:'',done:false,status:'Por hacer',assignee:'',startDate:'',dueDate:''},hours:{taskId:'',date:today(),hours:1,cost:35,notes:''},invoice:{orderId:data?.state.orders.find(o=>o.confirmed)?.id||'',title:'',date:today(),dueDate:dateOffset(30),policy:'fixed',amount:0,hourIds:[]},pay:{date:today()}};setForm({kind,record:{id:crypto.randomUUID(),demo:false,...defaults[kind],...structuredClone(record)}})}
 function changeView(v:string){setView(v);setProjectFocus(null);setProjectLens('board');setQuery('');setFilter('all');setCompanyFilter('all')}
 function askDelete(kind:Kind,id:string){setDeletion({action:'delete',kind,id})}
 function actions(kind:Kind,r:any,lead?:ReactNode){return <span className="row-actions">{lead}<button type="button" className="icon-button" title="Editar" aria-label={'Editar '+(r.title||r.name||labels[kind])} onClick={e=>{e.stopPropagation();open(kind==='invoices'?'editInvoice':kind,r)}}><Pencil size={14}/></button><button type="button" className="icon-button" title="Eliminar" aria-label={'Eliminar '+(r.title||r.name||labels[kind])} onClick={e=>{e.stopPropagation();askDelete(kind,r.id)}}><Trash2 size={14}/></button></span>}
 if(!data){return <main className="initial"><div className="brand">siarem.</div>{loading?<><p>Cargando tu espacio de trabajo…</p><Skeleton className="h-24 w-full"/><Skeleton className="h-48 w-full"/></>:<><p role="alert">{error}</p><button className="primary" onClick={load}>Volver a intentar</button><a href="/signin-with-chatgpt?return_to=/" target="_top">Iniciar sesión</a></>}</main>}
 if(data.onboarding)return <main className="login"><div className="brand">siarem.</div><h1>Prepara tu espacio de trabajo</h1><p>Si tu equipo ya usa Siarem, introduce su invitación.</p><form onSubmit={e=>{e.preventDefault();void send({action:join?'join':'onboard',name:org,token:join})}}><Field label="Nombre de tu empresa"><input value={org} onChange={e=>setOrg(e.target.value)}/></Field><Field label="Código de invitación · opcional"><input value={join} onChange={e=>setJoin(e.target.value)}/></Field>{error&&<p className="error" role="alert">{error}</p>}<button disabled={busy} className="primary">{join?'Unirme al equipo':'Crear mi espacio'}</button></form><small>El nuevo espacio incluye datos de demostración que puedes borrar.</small></main>;
 const s=data.state;const userName=data.user;
 const match=(...values:unknown[])=>matchesText(query,...values);
 const company=(id?:string)=>s.companies.find(c=>c.id===id);
 const leads=s.leads.filter(l=>match(l.name,l.contact,l.email,l.source,l.status,l.notes)&&(filter==='all'||(filter==='due'?!!l.nextDate&&l.nextDate<today()&&!['Convertido','Descartado'].includes(l.status):l.status===filter)));
 const openLeads=s.leads.filter(l=>!['Convertido','Descartado'].includes(l.status));
 const opps=pipelineOpportunities(s,{query,company:companyFilter});
 const focus=pipelineOpportunities(s,{query,company:companyFilter,focus:true,filter});
 const companies=s.companies.filter(c=>match(c.name,c.contact,c.email,c.phone));
 const quotes=s.quotes.filter(q=>{const o=s.opportunities.find(o=>o.id===q.opportunityId);return match(q.title,company(o?.companyId)?.name)&&(companyFilter==='all'||o?.companyId===companyFilter)});
 const orders=s.orders.filter(o=>match(o.title,company(companyForOrder(s,o.id))?.name)&&(companyFilter==='all'||companyForOrder(s,o.id)===companyFilter));
 const projects=s.projects.filter(p=>match(p.title,p.body,company(companyForOrder(s,p.orderId))?.name)&&(companyFilter==='all'||companyForOrder(s,p.orderId)===companyFilter));
 const invoices=s.invoices.filter(i=>match(i.title,company(companyForOrder(s,i.orderId))?.name)&&(companyFilter==='all'||companyForOrder(s,i.orderId)===companyFilter)&&(filter==='all'||(filter==='paid'?i.paid:!i.paid)));
 const openOpps=opps.filter(isOpenOpportunity);
 const freshLeads=openLeads.filter(l=>l.status==='Nuevo').length;
 const dueLeads=openLeads.filter(l=>!!l.nextDate&&l.nextDate<today());
 const readyLeads=openLeads.filter(l=>l.status==='Cualificado').length;
 const critical=openOpps.filter(o=>risk(s,o).level===2).length;
 const attention=openOpps.filter(o=>risk(s,o).level===1).length;
 const selectedCompany=company(selected?.companyId);const selectedOpp=s.opportunities.find(o=>o.id===selected?.opportunityId);
 const selectedTasks=s.followups.filter(t=>t.opportunityId===selectedOpp?.id).sort((a,b)=>Number(a.done)-Number(b.done)||a.dueDate.localeCompare(b.dueDate));
 const selectedNext=selectedOpp?pipelineNextAction(s,selectedOpp):null;
 const pendingTasks=selectedTasks.filter(task=>!task.done),completedTasks=selectedTasks.filter(task=>task.done);
 const remainingTasks=pendingTasks.filter(task=>task.id!==selectedNext?.taskId);
 const selectedInteractions=s.interactions.filter(i=>i.companyId===selected?.companyId&&(!selected?.opportunityId||i.opportunityId===selected.opportunityId||!i.opportunityId)).sort((a,b)=>b.date.localeCompare(a.date));
 const selectedOpen=!!selectedOpp&&isOpenOpportunity(selectedOpp),selectedRisk=selectedOpp?risk(s,selectedOpp):null;
 const selectedProject=selectedOpp?s.projects.find(p=>s.orders.some(o=>o.id===p.orderId&&s.quotes.some(q=>q.id===o.quoteId&&q.opportunityId===selectedOpp.id))):undefined;
 const companyOpps=s.opportunities.filter(o=>o.companyId===selected?.companyId);
 const historyTasks=selectedOpen?completedTasks:selectedTasks;
 const demo=s.companies.some(c=>c.demo);
 function movedToast(to:string,undo:Command){toast.success('Movida a '+to,{action:{label:'Deshacer',onClick:()=>void agent.current.send(undo)}})}
 async function stageChange(id:string,from:string,to:string){if(from===to||busy||saving.current||!isStage(to)||!isStage(from))return;setData(current=>current?.state?{...current,state:{...current.state,opportunities:current.state.opportunities.map(item=>item.id===id?{...item,stage:to}:item)}}:current);if(await send({action:'stage',id,stage:to,expectedStage:from}))movedToast(to,{action:'stage',id,stage:from as (typeof stages)[number],expectedStage:to});else {setData(current=>current?.state?{...current,state:{...current.state,opportunities:current.state.opportunities.map(item=>item.id===id&&item.stage===to?{...item,stage:from}:item)}}:current);void load()}}
 async function moveTask(task:State['delivery'][number],to:string){if(task.status===to||busy)return;const status=to as (typeof taskStatuses)[number];setData(current=>current?.state?{...current,state:{...current.state,delivery:current.state.delivery.map(item=>item.id===task.id?{...item,status,done:status==='Hecho'}:item)}}:current);if(await send({action:'save',kind:'delivery',record:{...task,status,done:status==='Hecho'}}))movedToast(to,{action:'save',kind:'delivery',record:task});else void load()}
 async function convertLead(id:string){const before=s.companies.length;const saved=await send({action:'convertLead',id});if(!saved?.state)return;const lead=saved.state.leads.find((item:State['leads'][number])=>item.id===id);const target=saved.state.companies.find((item:State['companies'][number])=>item.id===lead?.convertedCompanyId);toast.success(saved.state.companies.length===before&&target?`Lead convertido en ${target.name}, que ya existía. No se ha duplicado la empresa`:'Lead convertido. La empresa y la oportunidad conservan las notas');if(lead?.convertedCompanyId)setSelected({companyId:lead.convertedCompanyId,opportunityId:lead.convertedOpportunityId})}
 function table(headers:string[],rows:ReactNode[]){return rows.length?<Table><TableHeader><TableRow>{headers.map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows}</TableBody></Table>:<Blank filtered={!!query||companyFilter!=='all'||filter!=='all'}/>}
 const unpaid=s.invoices.filter(i=>!i.paid).length;
 const moduleStat:Record<string,string>={
  Foco:critical+attention?`${critical+attention} por atender`:'Nada urgente',
  Leads:openLeads.length?`${openLeads.length} en bandeja`:'Bandeja vacía',
  Pipeline:openOpps.length?eur(openOpps.reduce((sum,item)=>sum+item.amount,0)):'Sin abiertas',
  Empresas:`${s.companies.length} ${s.companies.length===1?'empresa':'empresas'}`,
  Ventas:`${s.quotes.length+s.orders.length} documentos`,
  Proyectos:`${s.projects.length} en marcha`,
  Facturas:unpaid?`${unpaid} por cobrar`:'Nada pendiente',
 };
 const currentProject=view==='Proyectos'&&projectFocus?s.projects.find(p=>p.id===projectFocus):undefined;
 const projectTaskList=currentProject?projectTasks(s,currentProject.id,query):[];
 function openProject(id:string|null){setProjectFocus(id);setProjectLens('board');setQuery('');setFilter('all');setCompanyFilter('all')}
 function projectSummary(p:State['projects'][number]){const order=s.orders.find(o=>o.id===p.orderId);return p.body||(order?`Pedido de ${company(companyForOrder(s,order.id))?.name||'la empresa'}`:'Proyecto interno')}
 function projectMetrics(p:State['projects'][number]){const order=s.orders.find(o=>o.id===p.orderId);const cost=projectCost(s,p.id);const all=s.delivery.filter(t=>t.projectId===p.id);return <div className="metrics"><div><span>Tareas hechas</span><strong>{all.filter(t=>t.status==='Hecho').length}<small>de {all.length}</small></strong></div>{order&&<div><span>Pedido</span><strong>{eur(total(order.lines))}</strong></div>}<div><span>Coste de horas</span><strong>{eur(cost)}</strong></div>{order&&<div><span>Margen</span><strong>{eur(total(order.lines)-cost)}</strong></div>}</div>}
 function projectScreen(){
  if(!currentProject){
    if(!projects.length)return <Blank filtered={!!query||companyFilter!=='all'} text="Crea el primer proyecto. También aparece uno al confirmar un pedido."/>;
    return <div className="project-index">{projects.map(p=>{const openTasks=s.delivery.filter(t=>t.projectId===p.id&&t.status!=='Hecho').length;return <button type="button" className="project-row" key={p.id} onClick={()=>openProject(p.id)}><span><b>{p.title}</b><small>{projectSummary(p)}</small></span><strong>{openTasks?openTasks+' abiertas':'Sin tareas abiertas'}</strong><ArrowRight size={16}/></button>})}</div>;
  }
  if(!projectTaskList.length)return <Blank filtered={!!query} text="Añade la primera tarea para organizar este proyecto."/>;
  if(projectLens==='roadmap')return <Roadmap tasks={projectTaskList} onOpen={task=>open('delivery',task)}/>;
  return <Board label="Tablero del proyecto" columns={taskStatuses.map((status,n)=>({key:status,label:status,tone:[0,1,3][n]}))} items={projectTaskList} columnOf={task=>task.status} busy={busy} onOpen={task=>open('delivery',task)} onMove={(task,to)=>void moveTask(task,to)} card={task=>{const mine=task.assignee===userName;return {title:task.title,subtitle:task.assignee||'Sin asignar',chip:<DueChip task={task}/>,tools:<><button type="button" className="icon-button" disabled={busy} title={mine?'Quitarme':'Asignarme'} aria-label={(mine?'Quitarme de ':'Asignarme ')+task.title} onClick={()=>void send({action:'save',kind:'delivery',record:{...task,assignee:mine?'':userName}})}>{mine?<UserMinus size={14}/>:<UserPlus size={14}/>}</button><button type="button" className="icon-button" title="Imputar horas" aria-label={'Imputar horas a '+task.title} onClick={()=>open('hours',{taskId:task.id})}><Clock3 size={14}/></button></>}}}/>;
 }
 const count:Record<string,number>={Foco:focus.length,Leads:leads.length,Pipeline:opps.length,Empresas:companies.length,Ventas:(filter==='orders'?0:quotes.length)+(filter==='quotes'?0:orders.length),Proyectos:currentProject?projectTaskList.length:projects.length,Facturas:invoices.length};
 const primary=view==='Proyectos'?(currentProject?{label:'Nueva tarea',run:()=>open('delivery',{projectId:currentProject.id,startDate:today(),dueDate:dateOffset(7)})}:{label:'Nuevo proyecto',run:()=>open('projects')}):{label:createLabel[createKind(view)],run:()=>open(createKind(view))};
 function formTitle(f:Form){if(f.kind==='pay')return 'Registrar cobro';if(f.kind==='invoice')return 'Generar factura';if(f.kind==='editInvoice')return 'Editar factura';const exists=((s as unknown as Record<string,{id:string}[]|undefined>)[f.kind])?.some(x=>x.id===f.record.id);if(f.kind==='hours'&&!exists)return 'Imputar horas';return exists?'Editar '+labels[f.kind]:(feminine.has(f.kind)?'Nueva ':'Nuevo ')+labels[f.kind]}
 const viewFilters=view==='Foco'?[['all','Por atender'],['2','Críticas'],['1','Atención'],['healthy','Al día']]:view==='Leads'?[['all','Todos'],['Nuevo','Nuevos'],['Contactado','Contactados'],['Cualificado','Cualificados'],['due','Vencidos'],['Convertido','Convertidos'],['Descartado','Descartados']]:view==='Ventas'?[['all','Todos'],['quotes','Presupuestos'],['orders','Pedidos']]:view==='Facturas'?[['all','Todas'],['pending','Pendientes'],['paid','Cobradas']]:[];
 return <div className="app-frame"><Toaster position="bottom-right" theme="dark"/><header className="topbar"><nav aria-label="Ubicación actual" className="topbar-path"><button type="button" className="brand-link" onClick={()=>changeView('Inicio')}>siarem<span>.</span></button>{view!=='Inicio'&&<><ChevronRight size={13}/>{currentProject?<><button type="button" className="crumb" onClick={()=>openProject(null)}>Proyectos</button><ChevronRight size={13}/><strong>{currentProject.title}</strong></>:<strong>{view}</strong>}</>}</nav><div className="topbar-tools">{demo&&<button type="button" className="demo-chip" title="Borrar los datos de demostración" onClick={()=>setDeletion({action:'deleteDemo'})}>Datos de demostración<Trash2 size={13}/></button>}<button type="button" ref={hermesTrigger} className="compact-action hermes-toggle" onClick={()=>setHermesOpen(true)}><Bot size={15}/> Hermes</button><span className="save-status" role="status"><span className={'status-dot'+(error?' is-error':'')}/>{busy?'Guardando…':loading?'Actualizando…':error?'Sin guardar':'Guardado'}</span><button type="button" className="crumb" onClick={()=>setTeam(true)}><Users size={16}/>{data.tenant}</button><a aria-label="Cerrar sesión" title="Cerrar sesión" href="/signout-with-chatgpt?return_to=/" target="_top"><LogOut size={16}/></a></div></header><main className={"content view-"+view}><div className="page-heading"><div>{view==='Inicio'&&<div className="eyebrow">{new Intl.DateTimeFormat('es-ES',{weekday:'long',day:'numeric',month:'long',timeZone:'Europe/Madrid'}).format(new Date())}</div>}<h1>{currentProject?currentProject.title:pageCopy[view].title}{view!=='Inicio'&&<span className="count">{count[view]}</span>}</h1><p>{currentProject?projectSummary(currentProject):pageCopy[view].text}</p></div>{view!=='Inicio'&&<div className="heading-actions">{currentProject&&actions('projects',currentProject)}<button className="primary" onClick={primary.run}><Plus size={16}/>{primary.label}</button></div>}</div>
 {view==='Inicio'&&<div className="module-list">{nav.map(n=><button type="button" className="module-entry" key={n.name} onClick={()=>changeView(n.name)}><n.icon size={20}/><span><b>{n.name}</b><small>{moduleDescriptions[n.name]}</small></span><strong>{moduleStat[n.name]}</strong><ArrowRight size={16}/></button>)}</div>}
 {error&&<div className="error-banner" role="alert"><span>{error}</span><button onClick={load}><RefreshCw size={14}/> Recargar datos</button></div>}
 {(view==='Foco'||view==='Leads'||view==='Facturas')&&<div className="metrics">{view==='Foco'&&<><button type="button" onClick={()=>changeView('Leads')}><span>Leads por trabajar</span><strong>{openLeads.length}</strong><span className="metric-note">Abrir bandeja de leads</span></button><button type="button" onClick={()=>setFilter('all')}><span>Oportunidades por atender</span><strong>{critical+attention}</strong><span className="metric-note"><b className="red">{critical} {critical===1?'crítica':'críticas'}</b> · {attention} cierre cerca</span></button><div><span>Importe en juego</span><strong>{eur(openOpps.reduce((a,o)=>a+o.amount,0))}</strong><span className="metric-note">{openOpps.length} abiertas</span></div></>}{view==='Leads'&&<><button type="button" onClick={()=>setFilter('Nuevo')}><span>Sin contactar</span><strong>{freshLeads}</strong></button><button type="button" onClick={()=>setFilter('due')}><span>Acción vencida</span><strong className={dueLeads.length?'red':''}>{dueLeads.length}</strong></button><button type="button" onClick={()=>setFilter('Cualificado')}><span>Listos para convertir</span><strong>{readyLeads}</strong></button></>}{view==='Facturas'&&<><button type="button" onClick={()=>setFilter('pending')}><span>Pendiente de cobro</span><strong>{eur(invoices.filter(i=>!i.paid).reduce((a,i)=>a+i.amount,0))}</strong><span className="metric-note">{invoices.filter(i=>!i.paid&&i.dueDate<today()).length} vencidas</span></button><button type="button" onClick={()=>setFilter('paid')}><span>Cobrado</span><strong>{eur(invoices.filter(i=>i.paid).reduce((a,i)=>a+i.amount,0))}</strong><span className="metric-note">{invoices.filter(i=>i.paid).length} facturas</span></button><div><span>Total facturado</span><strong>{eur(invoices.reduce((a,i)=>a+i.amount,0))}</strong></div></>}</div>}
 {currentProject&&projectMetrics(currentProject)}
 {view!=='Inicio'&&<section className={"working-surface surface-"+view}><div className="toolbar"><div className="search"><Search size={16}/><input aria-label="Buscar" placeholder={view==='Proyectos'?(currentProject?'Buscar tarea, responsable o fecha…':'Buscar proyecto…'):view==='Empresas'?'Buscar empresa, contacto o email…':view==='Leads'?'Buscar nombre, email o fuente…':'Buscar empresa u oportunidad…'} value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button type="button" onClick={()=>setQuery('')} aria-label="Limpiar búsqueda"><X size={14}/></button>}</div>{view!=='Empresas'&&view!=='Leads'&&!currentProject&&<Pick label="Filtrar por empresa" value={companyFilter} onChange={setCompanyFilter} options={[{value:'all',label:'Todas las empresas'},...s.companies.map(c=>({value:c.id,label:c.name}))]}/>}{currentProject?<div className="filters" role="group" aria-label="Vista del proyecto">{([['board','Tablero'],['roadmap','Roadmap']] as const).map(([v,l])=><button type="button" key={v} aria-pressed={projectLens===v} className={projectLens===v?'selected':''} onClick={()=>setProjectLens(v)}>{l}</button>)}</div>:<div className="filters">{viewFilters.map(([v,l])=><button type="button" key={v} aria-pressed={filter===v} className={filter===v?'selected':''} onClick={()=>setFilter(v)}>{l}</button>)}</div>}<a className="subtle export-link" download href={"/api/export?"+new URLSearchParams({view,q:query,filter,company:companyFilter,...(currentProject?{project:currentProject.id}:{})}).toString()}><Download size={14}/> Exportar CSV</a></div>
 {view==='Leads'&&table(['LEAD','FUENTE','ESTADO','PRÓXIMA ACCIÓN',''],leads.map(l=><TableRow key={l.id} className="clickable" onClick={()=>open('leads',l)}><TableCell><span className="lead-name"><span className="lead-avatar">{l.name.slice(0,1).toUpperCase()}</span><span><strong>{l.name}</strong><small>{l.contact||l.email||'Sin contacto'}</small></span></span></TableCell><TableCell><span className="source-pill">{l.source}</span></TableCell><TableCell><span className={'badge lead-'+l.status}><span className="status-dot"/>{l.status}</span></TableCell><TableCell>{l.status==='Convertido'||l.status==='Descartado'?<span className="soft">{l.status==='Convertido'?'En su oportunidad':'Sin acción'}</span>:(()=>{const late=!!l.nextDate&&l.nextDate<today();return <span className={late?'red':''}>{l.nextDate?(late?'Vencida · ':'')+shortDate(l.nextDate):'Sin fecha'}</span>})()}<small className="lead-note" title={l.notes||undefined}>{l.notes||'Sin notas todavía'}</small></TableCell><TableCell>{l.status==='Convertido'?<span className="row-actions">{l.convertedCompanyId&&<button type="button" className="compact-action" onClick={e=>{e.stopPropagation();setSelected({companyId:l.convertedCompanyId!,opportunityId:l.convertedOpportunityId})}}>Ver oportunidad</button>}</span>:actions('leads',l,l.status!=='Descartado'&&<button type="button" className="compact-action" disabled={busy} onClick={e=>{e.stopPropagation();void convertLead(l.id)}}>Convertir</button>)}</TableCell></TableRow>))}
 {view==='Foco'&&<FocusQueue state={s} opportunities={focus} filtered={!!query||companyFilter!=='all'||filter!=='all'} onOpen={openOpportunity} onPipeline={()=>changeView('Pipeline')}/>}
 {view==='Pipeline'&&<Board filtered={!!query||companyFilter!=='all'} onCreate={stage=>open('opportunities',{stage,...(companyFilter!=='all'?{companyId:companyFilter}:{})})} label="Tablero de oportunidades" columns={stages.map((stage,n)=>({key:stage,label:stage,tone:n,total:eur(opps.filter(o=>o.stage===stage).reduce((sum,o)=>sum+o.amount,0))}))} items={opps} columnOf={o=>o.stage} busy={busy} onOpen={openOpportunity} onMove={(o,to)=>void stageChange(o.id,o.stage,to)} card={o=>{const level=risk(s,o).level;const closed=o.stage==='Ganada'||o.stage==='Perdida';const next=pipelineNextAction(s,o);const date=next?.date;return {title:o.title,subtitle:company(o.companyId)?.name||'Sin empresa',aside:eur(o.amount),note:next?.title,meta:date?(date<today()?'Vencido · ':'')+shortDate(date):'Sin fecha',chip:closed?<span className={'badge tone-'+(o.stage==='Ganada'?'done':'open')}>{o.stage}</span>:<Badge level={level}>{plainStatus(level)}</Badge>}}}/>}
 {view==='Empresas'&&table(['EMPRESA','CONTACTO','EMAIL / TELÉFONO','OPORTUNIDADES','ÚLTIMO CONTACTO',''],companies.map(c=>{const last=s.interactions.filter(i=>i.companyId===c.id).reduce((a,i)=>i.date>a?i.date:a,'');const stale=!last||days(last)>=c.contactDays;return <TableRow key={c.id} className="clickable" onClick={()=>setSelected({companyId:c.id})}><TableCell><button className="record-link" onClick={e=>{e.stopPropagation();setSelected({companyId:c.id})}}><span className="company-icon">{c.name.slice(0,2).toUpperCase()}</span><span><strong>{c.name}</strong>{c.demo&&<small>Demostración</small>}</span></button></TableCell><TableCell>{c.contact||<span className="soft">Sin persona</span>}</TableCell><TableCell>{c.email||c.phone?<>{c.email||c.phone}{c.email&&c.phone&&<small>{c.phone}</small>}</>:<span className="amber">Falta email y teléfono</span>}</TableCell><TableCell>{s.opportunities.filter(o=>o.companyId===c.id).length}</TableCell><TableCell><span className={stale?'amber':''}>{last?shortDate(last):'Sin contactos'}</span><small>{last?`${days(last)===0?'Hoy':days(last)===1?'Ayer':`Hace ${days(last)} días`} · aviso a los ${c.contactDays}`:`Aviso a los ${c.contactDays} días`}</small></TableCell><TableCell>{actions('companies',c)}</TableCell></TableRow>}))}
 {view==='Ventas'&&<>{filter!=='orders'&&<><h3 className="subheading">Presupuestos</h3>{table(['PRESUPUESTO','EMPRESA','IMPORTE','ESTADO',''],quotes.map(q=><TableRow key={q.id}><TableCell><strong>{q.title}</strong><small>{q.lines.map(l=>l.description).join(' · ')}</small></TableCell><TableCell>{company(s.opportunities.find(o=>o.id===q.opportunityId)?.companyId)?.name}</TableCell><TableCell className="numeric">{eur(total(q.lines))}</TableCell><TableCell>{s.orders.some(o=>o.quoteId===q.id&&o.confirmed)?<Badge level={0}>Confirmado</Badge>:<Badge level={1}>Pendiente</Badge>}</TableCell><TableCell>{actions('quotes',q,!s.orders.some(o=>o.quoteId===q.id&&o.confirmed)&&<><button type="button" className="compact-action" disabled={busy} onClick={async()=>{if(await send({action:'confirm',id:q.id}))toast.success('Pedido confirmado y proyecto creado')}}>Confirmar pedido</button>{!s.orders.some(o=>o.quoteId===q.id)&&<button type="button" className="subtle" onClick={()=>open('orders',{quoteId:q.id,title:q.title,lines:q.lines,confirmed:false})}>Crear borrador</button>}</>)}</TableCell></TableRow>))}</>}{filter!=='quotes'&&<><h3 className="subheading">Pedidos</h3>{table(['PEDIDO','EMPRESA','IMPORTE','ESTADO',''],orders.map(o=><TableRow key={o.id}><TableCell><strong>{o.title}</strong><small>{o.lines.map(l=>policyLabel[l.policy]).join(' · ')}</small></TableCell><TableCell>{company(companyForOrder(s,o.id))?.name}</TableCell><TableCell className="numeric">{eur(total(o.lines))}</TableCell><TableCell><Badge level={o.confirmed?0:1}>{o.confirmed?'Confirmado':'Borrador'}</Badge></TableCell><TableCell>{actions('orders',o,o.confirmed?<button type="button" className="compact-action" onClick={()=>open('invoice',{orderId:o.id,policy:o.lines[0].policy})}>Generar factura</button>:<button type="button" className="compact-action" disabled={busy} onClick={async()=>{if(await send({action:'confirm',id:o.quoteId}))toast.success('Pedido confirmado y proyecto creado')}}>Confirmar pedido</button>)}</TableCell></TableRow>))}</>}</>}
 {view==='Proyectos'&&projectScreen()}
 {view==='Facturas'&&table(['FACTURA / EMPRESA','FECHA','VENCIMIENTO','IMPORTE','ESTADO',''],invoices.map(i=><TableRow key={i.id}><TableCell><strong>{i.title}</strong><small>{company(companyForOrder(s,i.orderId))?.name} · {policyLabel[i.policy]}</small></TableCell><TableCell>{i.date}</TableCell><TableCell className={!i.paid&&i.dueDate<today()?'red':''}>{i.dueDate}</TableCell><TableCell className="numeric">{eur(i.amount)}</TableCell><TableCell><Badge level={i.paid?0:1}>{i.paid?'Cobrada':'Pendiente'}</Badge>{i.paid&&<small>{s.payments.find(p=>p.invoiceId===i.id)?.date}</small>}</TableCell><TableCell>{actions('invoices',i,!i.paid&&<button type="button" className="compact-action" onClick={()=>open('pay',{invoiceId:i.id,amount:i.amount})}>Registrar cobro</button>)}</TableCell></TableRow>))}
 </section>}{(view==='Ventas'||view==='Facturas')&&<p className="fine-print">Importes en euros, sin impuestos.</p>}</main>
 <Sheet open={!!selected&&!!selectedCompany} onOpenChange={v=>{if(!v)setSelected(null)}}><SheetContent onCloseAutoFocus={event=>{if(detailReturnFocus.current?.isConnected){event.preventDefault();detailReturnFocus.current.focus()}detailReturnFocus.current=null}} showCloseButton={false} className="detail-panel"><SheetClose className="close-panel" aria-label="Cerrar panel"><X size={17}/></SheetClose><SheetHeader><div className="eyebrow">{selectedOpp?'OPORTUNIDAD':'EMPRESA'}{selectedCompany?.demo?' · DEMOSTRACIÓN':''}</div><SheetTitle>{selectedOpp?.title||selectedCompany?.name}</SheetTitle><SheetDescription>{selectedOpp?selectedCompany?.name+' · ':''}{selectedCompany?.contact||'Sin contacto principal'}{selectedCompany?.email?' · '+selectedCompany.email:''}</SheetDescription>{selectedOpp&&<div className="panel-status">{selectedOpen&&selectedRisk?<Badge level={selectedRisk.level}>{selectedRisk.label}</Badge>:<span className={'badge'+(selectedOpp.stage==='Ganada'?' tone-done':'')}><span className="status-dot"/>{selectedOpp.stage}</span>}<strong>{eur(selectedOpp.amount)}</strong></div>}</SheetHeader><div className="panel-body">
 {selectedOpp&&companyOpps.length>1&&<Field label="Oportunidad"><Pick label="Oportunidad del panel" value={selectedOpp.id} options={[{value:'',label:'Toda la empresa'},...companyOpps.map(o=>({value:o.id,label:o.title}))]} onChange={v=>setSelected(x=>x?{...x,opportunityId:v}:null)}/></Field>}
 {!selectedOpp&&selectedCompany&&<><div className="panel-actions">{actions('companies',selectedCompany,<button type="button" className="compact-action" onClick={()=>open('opportunities',{companyId:selectedCompany.id})}><Plus size={14}/> Oportunidad</button>)}</div><section className="panel-section" aria-labelledby="panel-opps"><div className="section-heading"><h3 id="panel-opps">Oportunidades <span className="count">{companyOpps.length}</span></h3></div>{companyOpps.length?<ul className="company-opps">{companyOpps.map(o=><li key={o.id}><button type="button" onClick={()=>setSelected(x=>x?{...x,opportunityId:o.id}:null)}><span><strong>{o.title}</strong><small>{o.stage} · {eur(o.amount)}</small></span><ChevronRight size={15}/></button></li>)}</ul>:<p className="muted">Esta empresa todavía no tiene oportunidades.</p>}</section></>}
 {selectedOpp&&selectedOpen&&<section className="panel-section" aria-labelledby="panel-followup"><div className="section-heading"><h3 id="panel-followup">Seguimiento</h3><button className="subtle" onClick={()=>open('followups')}><Plus size={14}/> Seguimiento</button></div>{selectedRisk&&selectedRisk.level>0&&<p className="panel-reason">{selectedRisk.reason}</p>}{selectedNext&&<div ref={el=>{nextActionRef.current=el}} className="next-step" role="group" aria-label="Siguiente acción"><small>SIGUIENTE ACCIÓN</small><strong>{selectedNext.title}</strong><span className={selectedNext.date&&selectedNext.date<today()?'red':''}>{selectedNext.date?(selectedNext.date<today()?'Vencida · ':'')+shortDate(selectedNext.date):'Sin fecha'}</span><div className="next-step-actions">{selectedNext.taskId?<><button className="primary" disabled={busy} onClick={async()=>{if(await send({action:'complete',id:selectedNext.taskId!})){toast.success('Seguimiento completado');requestAnimationFrame(()=>nextActionRef.current?.querySelector<HTMLButtonElement>('button')?.focus())}}}>Marcar hecha</button><button className="outline" onClick={()=>open('followups',pendingTasks.find(t=>t.id===selectedNext.taskId))}>Editar tarea</button></>:<button className="outline" onClick={()=>open('opportunities',selectedOpp)}>{selectedNext.defined?'Editar siguiente paso':'Definir siguiente paso'}</button>}<button className="outline" onClick={()=>setDraft(followupDraft(s,selectedOpp))}>Preparar mensaje <ArrowUpRight size={14}/></button></div></div>}{remainingTasks.length>0&&<><p className="panel-subhead">Después</p>{remainingTasks.map(t=><div className="task-row" key={t.id}><Checkbox aria-label={'Completar '+t.title} checked={false} disabled={busy} onCheckedChange={()=>void send({action:'complete',id:t.id})}/><span>{t.title}<small className={t.dueDate<today()?'red':''}>{shortDate(t.dueDate)}</small></span>{actions('followups',t)}</div>)}</>}</section>}
 {selectedOpp&&<section className="panel-section" aria-labelledby="panel-close"><div className="section-heading"><h3 id="panel-close" tabIndex={-1}>Cierre</h3>{actions('opportunities',selectedOpp)}</div><div className="close-grid"><Field label="Etapa"><Pick disabled={busy} label="Etapa" value={selectedOpp.stage} options={[...stages]} onChange={to=>void stageChange(selectedOpp.id,selectedOpp.stage,to)}/></Field><div className="close-date"><span>Cierre previsto</span><strong className={selectedOpen&&selectedOpp.closeDate<today()?'red':''}>{selectedOpen&&selectedOpp.closeDate<today()?'Vencido · ':''}{shortDate(selectedOpp.closeDate)}</strong></div></div>{selectedOpen?<div className="panel-actions"><button className="compact-action" onClick={()=>open('quotes',{opportunityId:selectedOpp.id,title:'Presupuesto · '+selectedOpp.title})}><Plus size={14}/> Presupuesto</button>{(['Ganada','Perdida'] as const).map(to=><button key={to} className="compact-action" disabled={busy} onClick={async()=>{await stageChange(selectedOpp.id,selectedOpp.stage,to);requestAnimationFrame(()=>document.getElementById('panel-close')?.focus())}}>Marcar {to.toLowerCase()}</button>)}</div>:<><p className="closed-notice">Oportunidad {selectedOpp.stage.toLowerCase()}. Cambia la etapa para reabrirla; el historial se conserva.</p>{selectedProject&&<div className="panel-actions"><button className="compact-action" onClick={()=>{setSelected(null);changeView('Proyectos');setProjectFocus(selectedProject.id)}}>Ver proyecto <ArrowRight size={14}/></button></div>}</>}</section>}
 {selectedCompany&&<section className="panel-section" aria-labelledby="panel-activity"><div className="section-heading"><h3 id="panel-activity">Actividad</h3><button className="subtle" onClick={()=>open('interactions')}><Plus size={14}/> Interacción</button></div><div className="timeline">{selectedInteractions.map(i=><article key={i.id}><div className="timeline-dot"/><header><strong>{i.kind}</strong><small>{shortDate(i.date)}</small>{actions('interactions',i)}</header><p>{i.notes}</p></article>)}</div>{!selectedInteractions.length&&<p className="muted">Todavía no hay contactos registrados.</p>}{historyTasks.length>0&&<details className="completed-followups"><summary>{selectedOpen?'Seguimientos completados':'Seguimientos'} ({historyTasks.length})</summary>{historyTasks.map(t=><div className="task-row" key={t.id}><Checkbox aria-label={(t.done?'Reabrir ':'Completar ')+t.title} checked={t.done} disabled={busy} onCheckedChange={()=>void send({action:'complete',id:t.id})}/><span className={t.done?'done':''}>{t.title}<small>{t.done?'':'Pendiente · '}{shortDate(t.dueDate)}</small></span>{actions('followups',t)}</div>)}</details>}</section>}
 </div></SheetContent></Sheet>
 <Dialog open={draft!==null} onOpenChange={v=>{if(!v)setDraft(null)}}><DialogContent showCloseButton={false}><DialogClose className="close-panel" aria-label="Cerrar"><X size={17}/></DialogClose><DialogHeader><DialogTitle>Preparar seguimiento</DialogTitle><DialogDescription>Revisa el texto antes de copiarlo o abrir tu correo.</DialogDescription></DialogHeader><textarea className="followup-draft" aria-label="Texto del seguimiento" value={draft||''} onChange={e=>setDraft(e.target.value)}/><div className="panel-actions"><button className="primary" onClick={async()=>{try{await navigator.clipboard.writeText(draft||'');toast.success('Seguimiento copiado')}catch{toast.error('No se pudo copiar. Selecciona el texto y cópialo.')}}}>Copiar texto</button>{selectedCompany?.email&&<a className="outline" href={`mailto:${encodeURIComponent(selectedCompany.email)}?subject=${encodeURIComponent(selectedOpp?.title||'Seguimiento')}&body=${encodeURIComponent(draft||'')}`}>Abrir correo</a>}</div></DialogContent></Dialog>
 <Dialog open={team} onOpenChange={setTeam}><DialogContent showCloseButton={false}><DialogClose className="close-panel" aria-label="Cerrar"><X size={17}/></DialogClose><DialogHeader><DialogTitle>{data.tenant} · Equipo</DialogTitle><DialogDescription>Los compañeros que acepten tu invitación compartirán los datos de este espacio.</DialogDescription></DialogHeader><p>{data.user} · {data.role==='owner'?'Propietario':'Miembro'}</p>{data.role==='owner'&&<><button className="primary" disabled={busy} onClick={()=>void send({action:'invite'})}>Crear invitación</button>{invite&&<><Field label="Código de un solo uso · válido durante 24 horas"><input readOnly value={invite}/></Field><button className="outline" onClick={async()=>{try{await navigator.clipboard.writeText(invite);toast.success('Invitación copiada')}catch{toast.error('Copia el código manualmente')}}}>Copiar código</button></>}</>}</DialogContent></Dialog>
 <AlertDialog open={!!deletion} onOpenChange={v=>{if(!v)setDeletion(null)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{deletion?.action==='deleteDemo'?'Borrar todos los datos de demostración':'Eliminar registro'}</AlertDialogTitle><AlertDialogDescription>{deletion?.action==='deleteDemo'?'Se eliminarán las empresas, oportunidades y documentos marcados como demostración. Tus datos propios se conservarán.':deletion?.kind==='invoices'?'Se eliminarán la factura y su cobro, si lo tiene. Las horas volverán a estar disponibles para facturar.':'Esta acción no se puede deshacer. Si hay documentos vinculados, tendrás que eliminarlos primero.'}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><button className="danger" disabled={busy} onClick={async()=>{if(deletion&&await send(deletion)){setDeletion(null);toast.success('Datos eliminados')}}}>Eliminar</button></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <Dialog open={!!form} onOpenChange={v=>{if(!v)setForm(null)}}><DialogContent onCloseAutoFocus={event=>{event.preventDefault();formReturnFocus.current?.focus()}} showCloseButton={false} className="form-dialog"><DialogHeader><DialogTitle>{form?formTitle(form):''}</DialogTitle><DialogDescription className="sr-only">Formulario de {labels[form?.kind||'companies']}</DialogDescription></DialogHeader>{form&&<RecordForm key={form.record.id} form={form} state={s} busy={busy} error={formError} refresh={load} onSubmit={async(record:any)=>{let cmd:any={action:'save',kind:form.kind,record};if(form.kind==='invoice')cmd={...record,action:'invoice',id:record.orderId};if(form.kind==='editInvoice')cmd={...record,action:'editInvoice'};if(form.kind==='pay')cmd={action:'pay',id:record.invoiceId,date:record.date};if(await send(cmd)){setForm(null);toast.success('Guardado')}}}/>}<DialogClose className="close-panel" aria-label="Cerrar formulario"><X size={17}/></DialogClose></DialogContent></Dialog>
 <HermesPanel onRestoreFocus={()=>hermesTrigger.current?.focus()} open={hermesOpen} context={hermesBrief(view,s)} onClose={()=>setHermesOpen(false)}/>
 </div>
}
function RecordForm({form,state:s,busy,error,refresh,onSubmit}:{form:Form;state:State;busy:boolean;error:string;refresh:()=>void;onSubmit:(r:any)=>Promise<void>}){
 const [r,setR]=useState<any>(form.record);const k=form.kind;
 const set=(key:string,v:any)=>setR((old:any)=>({...old,[key]:v}));
 const input=(key:string,label:string,type='text',props:any={})=><Field label={label}><input type={type} value={r[key]??''} onChange={e=>set(key,type==='number'?(e.target.value===''?'':Number(e.target.value)):e.target.value)} onInput={e=>{if(type==='date')set(key,e.currentTarget.value)}} {...props}/></Field>;
 const pick=(key:string,label:string,options:any[])=><Field label={label}><Pick value={String(r[key]??'')} onChange={v=>set(key,key==='lineIndex'?Number(v):v)} label={label} options={options}/></Field>;
 const oppOptions=[{value:'',label:'Selecciona una oportunidad'},...s.opportunities.map(o=>({value:o.id,label:`${s.companies.find(c=>c.id===o.companyId)?.name} · ${o.title}`}))];
 const taskOptions=[{value:'',label:'Selecciona una tarea'},...s.delivery.map(t=>({value:t.id,label:`${s.projects.find(p=>p.id===t.projectId)?.title} · ${t.title}`}))];
 const order=s.orders.find(o=>o.id===r.orderId);
 const invoiced=(policy:string)=>s.invoices.filter(i=>i.orderId===order?.id&&i.policy===policy).reduce((a,i)=>a+i.amount,0);
 const eligibleHours=s.hours.filter(h=>{const t=s.delivery.find(t=>t.id===h.taskId);const p=s.projects.find(p=>p.id===t?.projectId);return p?.orderId===order?.id&&order?.lines[t?.lineIndex??-1]?.policy==='hours'&&!s.invoices.some(i=>i.hourIds.includes(h.id))});
 return <form className="record-form" noValidate onSubmit={e=>{e.preventDefault();void onSubmit(r)}}>
 {k==='leads'&&<>{input('name','Empresa o contacto *')}{input('contact','Persona de contacto')}{input('email','Email','email')}{input('phone','Teléfono','tel')}{pick('source','Origen',[...leadSources])}{pick('status','Estado',leadStatuses.filter(status=>status!=='Convertido'||r.status==='Convertido'))}{input('nextDate','Fecha de la próxima acción','date')}<Field label="Qué sabemos"><textarea value={r.notes} onChange={e=>set('notes',e.target.value)} placeholder="Interés, contexto y por qué merece seguimiento"/></Field>{r.status==='Convertido'&&<p className="muted">Este lead ya es una oportunidad. El historial se conserva en la empresa.</p>}</>}
 {k==='companies'&&<>{input('name','Nombre de la empresa *')}{input('contact','Persona de contacto')}{input('email','Email','email')}{input('phone','Teléfono','tel')}{input('contactDays','Días sin contacto para marcar riesgo *','number',{min:1,max:90})}</>}
 {k==='opportunities'&&<>{pick('companyId','Empresa *',[{value:'',label:'Selecciona una empresa'},...s.companies.map(c=>({value:c.id,label:c.name}))])}{input('title','Nombre de la oportunidad *')}{input('amount','Importe estimado (€) *','number',{min:0,step:.01})}{pick('stage','Etapa',[...stages])}{input('closeDate','Fecha de cierre *','date')}{input('nextStep','Siguiente paso')}{input('nextDate','Fecha del siguiente paso','date')}</>}
 {k==='interactions'&&<>{pick('kind','Tipo de contacto',['Llamada','Email','Reunión','Nota'])}{input('date','Fecha *','date')}<Field label="Qué habéis hablado *"><textarea value={r.notes} onChange={e=>set('notes',e.target.value)} autoFocus/></Field></>}
 {k==='followups'&&<>{pick('opportunityId','Oportunidad *',oppOptions)}{input('title','Qué hay que hacer *')}{input('dueDate','Fecha de seguimiento *','date')}</>}
 {(k==='quotes'||k==='orders')&&<>{k==='quotes'?pick('opportunityId','Oportunidad *',oppOptions):pick('quoteId','Presupuesto de origen *',s.quotes.map(q=>({value:q.id,label:q.title})))}{input('title','Nombre del documento *')}<h3>Líneas de servicio</h3>{r.confirmed&&<p className="muted">Pedido confirmado: puedes cambiar su nombre. Sus líneas se conservan para mantener la trazabilidad.</p>}{r.lines.map((l:any,i:number)=>{const patch=(key:string,value:any)=>set('lines',r.lines.map((x:any,n:number)=>n===i?{...x,[key]:value}:x));return <fieldset className="service-line" key={i} disabled={r.confirmed}><legend>Servicio {i+1}</legend><Field label="Descripción del servicio *"><input value={l.description} onChange={e=>patch('description',e.target.value)}/></Field><div className="form-grid"><Field label={l.policy==='hours'?'Horas previstas *':'Cantidad *'}><input type="number" min="0.01" step="0.01" value={l.quantity} onChange={e=>patch('quantity',Number(e.target.value))}/></Field><Field label={l.policy==='hours'?'Precio por hora (€) *':'Precio unitario (€) *'}><input type="number" min="0" step="0.01" value={l.price} onChange={e=>patch('price',Number(e.target.value))}/></Field></div><Field label="Política de facturación"><Pick value={l.policy} onChange={v=>patch('policy',v)} label="Política de facturación" options={Object.entries(policyLabel).map(([value,label])=>({value,label}))}/></Field><Field label="Tareas del proyecto · una por línea *"><textarea value={l.tasks} onChange={e=>patch('tasks',e.target.value)}/></Field>{r.lines.length>1&&<button type="button" className="subtle red" onClick={()=>set('lines',r.lines.filter((_:any,n:number)=>n!==i))}>Quitar servicio</button>}</fieldset>})}<button disabled={r.confirmed} type="button" className="outline" onClick={()=>set('lines',[...r.lines,{description:'',quantity:1,price:0,policy:'fixed',tasks:'Entrega y revisión'}])}><Plus size={14}/> Añadir línea</button><div className="form-total">Total del documento <strong>{eur(total(r.lines))}</strong></div></>}
 {k==='projects'&&<>{input('title','Nombre del proyecto *')}<Field label="Descripción"><textarea value={r.body||''} onChange={e=>set('body',e.target.value)} placeholder="Qué hay que entregar y para quién"/></Field></>}
 {k==='delivery'&&<>{input('title','Tarea *')}{pick('status','Estado',[...taskStatuses])}{input('assignee','Asignada a','text',{placeholder:'Nombre de la persona'})}{input('startDate','Fecha de inicio','date')}{input('dueDate','Fecha objetivo','date')}{s.orders.find(o=>o.id===s.projects.find(p=>p.id===r.projectId)?.orderId)&&pick('lineIndex','Servicio del pedido',(s.orders.find(o=>o.id===s.projects.find(p=>p.id===r.projectId)?.orderId)?.lines||[]).map((l,i)=>({value:String(i),label:l.description})))}</>}
 {k==='hours'&&<>{pick('taskId','Tarea del proyecto *',taskOptions)}{input('date','Fecha *','date')}{input('hours','Horas imputadas *','number',{min:.01,max:24,step:.25})}{input('cost','Coste interno por hora (€) *','number',{min:0,step:.01})}{input('notes','Trabajo realizado')}<p className="muted">Coste imputado: {eur((Number(r.hours)||0)*(Number(r.cost)||0))}</p></>}
 {(k==='invoice'||k==='editInvoice')&&<>{k==='invoice'&&<><Field label="Pedido confirmado *"><Pick value={r.orderId} onChange={v=>{const o=s.orders.find(o=>o.id===v);setR({...r,orderId:v,policy:o?.lines[0].policy||'fixed',hourIds:[]})}} label="Pedido confirmado" options={[{value:'',label:'Selecciona un pedido'},...s.orders.filter(o=>o.confirmed).map(o=>({value:o.id,label:o.title}))]}/></Field>{pick('policy','Política de facturación',Array.from(new Set(order?.lines.map(l=>l.policy)||[])).map(value=>({value,label:policyLabel[value]})))}</>}{input('title','Número o referencia de factura *')}{input('date','Fecha de emisión *','date')}{input('dueDate','Fecha de vencimiento *','date')}{k==='invoice'&&r.policy==='milestones'&&input('amount','Importe del hito (€) *','number',{min:.01,step:.01})}{k==='invoice'&&r.policy!=='hours'&&<p className="form-total">Pendiente de facturar <strong>{eur(total(order?.lines.filter(l=>l.policy===r.policy)||[])-invoiced(r.policy))}</strong></p>}{k==='invoice'&&r.policy==='hours'&&<><h3>Horas pendientes de facturar</h3>{eligibleHours.map(h=><label className="task-row" key={h.id}><Checkbox checked={r.hourIds.includes(h.id)} onCheckedChange={checked=>set('hourIds',checked?[...r.hourIds,h.id]:r.hourIds.filter((id:string)=>id!==h.id))}/><span>{s.delivery.find(t=>t.id===h.taskId)?.title}<small>{h.date} · {h.hours} h</small></span></label>)}{!eligibleHours.length&&<p className="muted">No hay horas pendientes para este pedido.</p>}</>}</>}
 {k==='pay'&&<><p className="form-total">Cobro completo <strong>{eur(r.amount)}</strong></p>{input('date','Fecha del cobro *','date')}</>}
 {error&&<div className="error" role="alert">{error}<button type="button" className="subtle" onClick={refresh}>Recargar datos conservando el formulario</button></div>}<button className="primary save-button" disabled={busy}>{busy?'Guardando…':k==='invoice'?'Generar factura':k==='pay'?'Registrar cobro':'Guardar'}</button>
 </form>
}
