'use client';
import { useEffect,useRef,useState, type PointerEvent, type ReactNode } from 'react';
import { Crosshair,Columns3,Building2,FileText,FolderKanban,Receipt,Inbox,Search,Plus,ArrowUpRight,ArrowRight,Download,Clock3,ChevronRight,Trash2,Pencil,Users,LogOut,RefreshCw,X,GripVertical } from 'lucide-react';
import { SidebarProvider,Sidebar as BaseSidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger,SidebarInset,useSidebar } from '@/components/ui/sidebar';
import { Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription,SheetClose } from '@/components/ui/sheet';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogClose } from '@/components/ui/dialog';
import { AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel } from '@/components/ui/alert-dialog';
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from '@/components/ui/select';
import { Table,TableHeader,TableBody,TableHead,TableRow,TableCell } from '@/components/ui/table';
import { Checkbox } from '@/components/ui/checkbox';
import { Skeleton } from '@/components/ui/skeleton';
import { Empty,EmptyHeader,EmptyTitle,EmptyDescription } from '@/components/ui/empty';
import { Toaster } from '@/components/ui/sonner';
import { toast } from 'sonner';
import { stages,today,dateOffset,eur,total,risk,projectCost,companyForOrder,leadSources,leadStatuses, type State,type Kind,type Command } from '@/lib/crm';
type Data={state:State;revision:number;tenant:string;role:string;user:string;onboarding?:boolean};
type Form={kind:Kind|'invoice'|'editInvoice'|'pay';record:any};
const nav=[{name:'Foco',icon:Crosshair},{name:'Leads',icon:Inbox},{name:'Pipeline',icon:Columns3},{name:'Empresas',icon:Building2},{name:'Ventas',icon:FileText},{name:'Proyectos',icon:FolderKanban},{name:'Facturas',icon:Receipt}];
const labels:Record<string,string>={leads:'lead',companies:'empresa',opportunities:'oportunidad',interactions:'interacción',followups:'tarea de seguimiento',quotes:'presupuesto',orders:'pedido',delivery:'tarea de entrega',hours:'parte de horas',invoice:'factura',editInvoice:'factura',pay:'cobro'};
const policyLabel:Record<string,string>={fixed:'Precio fijo',milestones:'Hitos',hours:'Horas'};
const pageCopy:Record<string,{title:string;text:string}>={
 Foco:{title:'Qué hacer ahora',text:'Leads sin cualificar y oportunidades que se están enfriando.'},
 Leads:{title:'Bandeja de leads',text:'Contactos previos a una oportunidad. Conviértelos cuando haya interés real.'},
 Pipeline:{title:'Oportunidades',text:'Arrastra cada tarjeta a la columna que le toca. Si prefieres, pulsa Mover.'},
 Empresas:{title:'Empresas',text:'Con quién hablas y cada cuánto hay que retomar el contacto.'},
 Ventas:{title:'Ventas',text:'Presupuestos y pedidos ligados a una oportunidad.'},
 Proyectos:{title:'Proyectos',text:'Entrega, horas y margen del trabajo ya ganado.'},
 Facturas:{title:'Facturas',text:'Lo pendiente de cobro y lo ya cobrado.'},
};
const createKind=(view:string):Form['kind']=>view==='Empresas'?'companies':view==='Ventas'?'quotes':view==='Facturas'?'invoice':view==='Proyectos'?'hours':view==='Pipeline'?'opportunities':'leads';
const createLabel:Record<string,string>={companies:'Nueva empresa',quotes:'Nuevo presupuesto',invoice:'Generar factura',hours:'Imputar horas',opportunities:'Nueva oportunidad',leads:'Nuevo lead'};
function Pick({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:(string|{value:string;label:string})[];label:string}){return <Select value={value||'__empty'} onValueChange={v=>onChange(v==='__empty'?'':v)}><SelectTrigger aria-label={label} className="picker"><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{options.map(o=>{const v=typeof o==='string'?o:o.value;return <SelectItem key={v||'empty'} value={v||'__empty'}>{typeof o==='string'?o:o.label}</SelectItem>})}</SelectContent></Select>}
function Sidebar({children,className}:{children:ReactNode;className:string}){const {isMobile,openMobile,setOpenMobile}=useSidebar();if(!isMobile)return <BaseSidebar collapsible="icon" className={className}>{children}</BaseSidebar>;return <Sheet open={openMobile} onOpenChange={setOpenMobile}><SheetContent side="left" showCloseButton={false} className="mobile-navigation siarem-sidebar"><SheetHeader className="sr-only"><SheetTitle>Navegación de Siarem</SheetTitle><SheetDescription>Selecciona una pantalla del espacio comercial.</SheetDescription></SheetHeader><SheetClose className="close-panel" aria-label="Cerrar navegación"><X size={17}/></SheetClose>{children}</SheetContent></Sheet>}
function NavItem({name,children,onClick}: {name:string;children:ReactNode;onClick:()=>void}){const {setOpenMobile}=useSidebar();return <SidebarMenuButton tooltip={name} onClick={()=>{onClick();setOpenMobile(false)}} aria-label={name}>{children}</SidebarMenuButton>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
function Blank({filtered=false,text='Crea el primer registro para empezar.'}:{filtered?:boolean;text?:string}){return <Empty className="empty"><EmptyHeader><EmptyTitle>{filtered?'Sin resultados':'Todavía no hay registros'}</EmptyTitle><EmptyDescription>{filtered?'Prueba otro término o cambia los filtros.':text}</EmptyDescription></EmptyHeader></Empty>}
function Badge({level,children}:{level:number;children:ReactNode}){return <span className={'badge risk-'+level}><span className="status-dot"/>{children}</span>}
function plainStatus(level:number){return level===2?'Hay que actuar':level===1?'Revisar pronto':'En orden'}
function isStage(value:string): value is (typeof stages)[number]{return (stages as readonly string[]).includes(value)}
function PipelineBoard({opportunities,companyName,riskOf,busy,onOpen,onMove}:{opportunities:State['opportunities'];companyName:(id:string)=>string;riskOf:(id:string)=>number;busy:boolean;onOpen:(companyId:string,opportunityId:string)=>void;onMove:(id:string,from:string,to:string)=>void}){
 const [dragId,setDragId]=useState<string|null>(null),[over,setOver]=useState<string|null>(null),[moving,setMoving]=useState<string|null>(null);
 const start=useRef<{x:number;y:number;id:string;companyId:string;stage:string;active:boolean;node:HTMLElement}|null>(null);
 function columnAt(x:number,y:number){return document.elementFromPoint(x,y)?.closest('[data-stage]')?.getAttribute('data-stage')??null}
 function down(event:PointerEvent<HTMLElement>,item:State['opportunities'][number]){if(event.button!==0||busy)return;if((event.target as HTMLElement).closest('button,a'))return;start.current={x:event.clientX,y:event.clientY,id:item.id,companyId:item.companyId,stage:item.stage,active:false,node:event.currentTarget};event.currentTarget.setPointerCapture(event.pointerId)}
 function move(event:PointerEvent<HTMLElement>){const origin=start.current;if(!origin)return;if(!origin.active&&Math.hypot(event.clientX-origin.x,event.clientY-origin.y)<8)return;if(!origin.active){origin.active=true;origin.node.style.pointerEvents='none';setDragId(origin.id)}setOver(columnAt(event.clientX,event.clientY))}
 function up(event:PointerEvent<HTMLElement>){const origin=start.current;start.current=null;if(!origin)return;const stage=columnAt(event.clientX,event.clientY);origin.node.style.pointerEvents='';setDragId(null);setOver(null);if(!origin.active){onOpen(origin.companyId,origin.id);return}if(stage&&stage!==origin.stage)onMove(origin.id,origin.stage,stage)}
 function cancel(){if(start.current)start.current.node.style.pointerEvents='';start.current=null;setDragId(null);setOver(null)}
 return <><p className="pipeline-hint">Mantén pulsada una tarjeta y suéltala en otra columna. En el móvil, desliza el tablero para ver todas.</p><div className="pipeline" aria-label="Tablero de oportunidades">{stages.map((stage,n)=>{const items=opportunities.filter(item=>item.stage===stage);return <section className={'pipeline-column'+(over===stage&&dragId?' drop-over':'')} data-stage={stage} key={stage}><header><span className={'pipeline-dot stage-'+n}/><h3>{stage}</h3><span>{items.length}</span></header><div className="pipeline-total">{eur(items.reduce((sum,item)=>sum+item.amount,0))}</div>{items.map(item=>{const level=riskOf(item.id);return <article className={'opportunity'+(dragId===item.id?' dragging':'')} key={item.id} onPointerDown={event=>down(event,item)} onPointerMove={move} onPointerUp={up} onPointerCancel={cancel}><div className="record-title"><GripVertical className="drag-grip" size={16} aria-hidden/><span>{companyName(item.companyId)}</span><button type="button" aria-label={'Mover '+item.title} onClick={event=>{event.stopPropagation();setMoving(current=>current===item.id?null:item.id)}}>Mover</button></div><p>{item.title}</p><strong className="opportunity-amount">{eur(item.amount)}</strong>{item.nextStep&&<small>Siguiente: {item.nextStep}</small>}<Badge level={level}>{plainStatus(level)}</Badge>{moving===item.id&&<div className="move-choices">{stages.filter(option=>option!==item.stage).map(option=><button type="button" key={option} disabled={busy} onClick={()=>{setMoving(null);onMove(item.id,item.stage,option)}}>{option}</button>)}</div>}</article>})}{!items.length&&<p className="column-empty">{over===stage&&dragId?'Suelta aquí':'Nada por aquí'}</p>}</section>})}</div></>
}
export default function CRM(){
 const [data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [view,setView]=useState('Foco'),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[companyFilter,setCompanyFilter]=useState('all');
 const [selected,setSelected]=useState<{companyId:string;opportunityId?:string}|null>(null),[form,setForm]=useState<Form|null>(null),[formError,setFormError]=useState('');
 const [deletion,setDeletion]=useState<Command|null>(null),[undo,setUndo]=useState<{id:string;from:string;to:string}|null>(null);
 const [team,setTeam]=useState(false),[invite,setInvite]=useState(''),[draft,setDraft]=useState<string|null>(null);
 const [org,setOrg]=useState('Mi empresa'),[join,setJoin]=useState('');
 async function load(){setLoading(true);try{const r=await fetch('/api/crm',{cache:'no-store'});const d=await r.json() as any;if(!r.ok)throw new Error(d.error);setData(d);setError('')}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const agent=useRef<{data:Data|null;send:(command:Command)=>Promise<false|{state?:State}>}>({data:null,send:async()=>false});
 useEffect(()=>{const context=(document as {modelContext?:{registerTool?:(tool:object,options:{signal:AbortSignal})=>Promise<unknown>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const signal=lifecycle.signal;const register=(tool:object)=>void Promise.resolve(context.registerTool!(tool,{signal})).catch(()=>{});register({name:'navigate_siarem',description:'Abre una pantalla del CRM. No modifica registros.',inputSchema:{type:'object',properties:{view:{type:'string',enum:nav.map(n=>n.name)}},required:['view'],additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:{view?:string})=>{if(!input.view||!nav.some(n=>n.name===input.view))throw new Error('Pantalla no válida');setView(input.view);setQuery('');setFilter('all');return {view:input.view}}});register({name:'list_siarem_pipeline',description:'Lista las oportunidades del tablero: empresa, importe y columna.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>{const state=agent.current.data?.state;if(!state)throw new Error('El espacio todavía no está cargado');return state.opportunities.map(item=>({id:item.id,title:item.title,stage:item.stage,amount:item.amount,company:state.companies.find(company=>company.id===item.companyId)?.name??''}))}});register({name:'move_siarem_opportunity',description:'Mueve una oportunidad a otra columna. Es la misma acción que arrastrar la tarjeta.',inputSchema:{type:'object',properties:{id:{type:'string'},stage:{type:'string',enum:[...stages]}},required:['id','stage'],additionalProperties:false},execute:async(input:{id?:string;stage?:string})=>{const state=agent.current.data?.state;const current=state?.opportunities.find(item=>item.id===input.id);if(!current||!input.stage||!isStage(input.stage))throw new Error('No encuentro esa oportunidad o la columna no existe');const saved=await agent.current.send({action:'stage',id:current.id,stage:input.stage,expectedStage:current.stage});if(!saved)throw new Error('No se pudo mover');return {id:current.id,from:current.stage,stage:input.stage}}});return()=>lifecycle.abort()},[]);
 async function send(command:Command|any){if(busy)return false;setBusy(true);try{const r=await fetch('/api/crm',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...command,revision:data?.revision})});const d=await r.json() as any;if(!r.ok)throw new Error(d.error);if(d.token)setInvite(d.token);else setData(d);setError('');return d}catch(e){const msg=(e as Error).message;setFormError(msg);setError(msg);toast.error(msg);return false}finally{setBusy(false)}}
 agent.current={data,send};
 function open(kind:Form['kind'],record:any={}){setFormError('');const defaults:Record<string,any>={leads:{name:'',contact:'',email:'',phone:'',source:'Referencia',status:'Nuevo',notes:'',nextDate:dateOffset(7),createdAt:today()},companies:{name:'',contact:'',email:'',phone:'',contactDays:30},opportunities:{companyId:selected?.companyId||data?.state.companies[0]?.id||'',title:'',amount:0,stage:stages[0],closeDate:dateOffset(14),nextStep:'',nextDate:'',createdAt:today()},interactions:{companyId:selected?.companyId,opportunityId:selected?.opportunityId||'',kind:'Llamada',date:today(),notes:''},followups:{opportunityId:selected?.opportunityId,title:'',dueDate:today(),done:false},quotes:{opportunityId:selected?.opportunityId||data?.state.opportunities[0]?.id||'',title:'',lines:[{description:'',quantity:1,price:0,policy:'fixed',tasks:'Preparación\nEjecución\nEntrega y revisión'}]},delivery:{projectId:'',lineIndex:0,title:'',done:false},hours:{taskId:'',date:today(),hours:1,cost:35,notes:''},invoice:{orderId:data?.state.orders.find(o=>o.confirmed)?.id||'',title:'',date:today(),dueDate:dateOffset(30),policy:'fixed',amount:0,hourIds:[]},pay:{date:today()}};setForm({kind,record:{id:crypto.randomUUID(),demo:false,...defaults[kind],...structuredClone(record)}})}
 function changeView(v:string){setView(v);setQuery('');setFilter('all');setCompanyFilter('all')}
 function askDelete(kind:Kind,id:string){setDeletion({action:'delete',kind,id})}
 function actions(kind:Kind,r:any){return <span className="row-actions"><button aria-label={'Editar '+(r.title||r.name||labels[kind])} onClick={e=>{e.stopPropagation();open(kind==='invoices'?'editInvoice':kind,r)}}><Pencil size={14}/></button><button aria-label={'Eliminar '+(r.title||r.name||labels[kind])} onClick={e=>{e.stopPropagation();askDelete(kind,r.id)}}><Trash2 size={14}/></button></span>}
 if(!data){return <main className="initial"><div className="brand">siarem.</div>{loading?<><p>Cargando tu espacio de trabajo…</p><Skeleton className="h-24 w-full"/><Skeleton className="h-48 w-full"/></>:<><p role="alert">{error}</p><button className="primary" onClick={load}>Volver a intentar</button><a href="/signin-with-chatgpt?return_to=/" target="_top">Iniciar sesión</a></>}</main>}
 if(data.onboarding)return <main className="login"><div className="brand">siarem.</div><h1>Prepara tu espacio de trabajo</h1><p>Si tu equipo ya usa Siarem, introduce su invitación.</p><form onSubmit={e=>{e.preventDefault();void send({action:join?'join':'onboard',name:org,token:join})}}><Field label="Nombre de tu empresa"><input value={org} onChange={e=>setOrg(e.target.value)}/></Field><Field label="Código de invitación · opcional"><input value={join} onChange={e=>setJoin(e.target.value)}/></Field>{error&&<p className="error" role="alert">{error}</p>}<button disabled={busy} className="primary">{join?'Unirme al equipo':'Crear mi espacio'}</button></form><small>El nuevo espacio incluye datos de demostración que puedes borrar.</small></main>;
 const s=data.state;
 const match=(...v:unknown[])=>v.join(' ').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().includes(query.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase());
 const company=(id?:string)=>s.companies.find(c=>c.id===id);
 const leads=s.leads.filter(l=>match(l.name,l.contact,l.email,l.source,l.status,l.notes)&&(filter==='all'||(filter==='due'?!!l.nextDate&&l.nextDate<today()&&!['Convertido','Descartado'].includes(l.status):l.status===filter)));
 const openLeads=s.leads.filter(l=>!['Convertido','Descartado'].includes(l.status));
 const opps=s.opportunities.filter(o=>match(o.title,company(o.companyId)?.name,o.nextStep,o.stage)&&(companyFilter==='all'||o.companyId===companyFilter));
 const focus=opps.filter(o=>filter==='all'?risk(s,o).level>0:filter==='healthy'?risk(s,o).level===0:String(risk(s,o).level)===filter).sort((a,b)=>risk(s,b).level-risk(s,a).level||(a.nextDate||a.closeDate).localeCompare(b.nextDate||b.closeDate));
 const companies=s.companies.filter(c=>match(c.name,c.contact,c.email,c.phone));
 const quotes=s.quotes.filter(q=>{const o=s.opportunities.find(o=>o.id===q.opportunityId);return match(q.title,company(o?.companyId)?.name)&&(companyFilter==='all'||o?.companyId===companyFilter)});
 const orders=s.orders.filter(o=>match(o.title,company(companyForOrder(s,o.id))?.name)&&(companyFilter==='all'||companyForOrder(s,o.id)===companyFilter));
 const projects=s.projects.filter(p=>match(p.title,company(companyForOrder(s,p.orderId))?.name)&&(companyFilter==='all'||companyForOrder(s,p.orderId)===companyFilter));
 const invoices=s.invoices.filter(i=>match(i.title,company(companyForOrder(s,i.orderId))?.name)&&(companyFilter==='all'||companyForOrder(s,i.orderId)===companyFilter)&&(filter==='all'||(filter==='paid'?i.paid:!i.paid)));
 const openOpps=s.opportunities.filter(o=>o.stage!=='Ganada'&&o.stage!=='Perdida');
 const freshLeads=openLeads.filter(l=>l.status==='Nuevo').length;
 const dueLeads=openLeads.filter(l=>!!l.nextDate&&l.nextDate<today());
 const readyLeads=openLeads.filter(l=>l.status==='Cualificado').length;
 const critical=s.opportunities.filter(o=>risk(s,o).level===2).length;
 const attention=s.opportunities.filter(o=>risk(s,o).level===1).length;
 const selectedCompany=company(selected?.companyId);const selectedOpp=s.opportunities.find(o=>o.id===selected?.opportunityId);
 const selectedTasks=s.followups.filter(t=>t.opportunityId===selectedOpp?.id).sort((a,b)=>Number(a.done)-Number(b.done)||a.dueDate.localeCompare(b.dueDate));
 const selectedInteractions=s.interactions.filter(i=>i.companyId===selected?.companyId&&(!selected?.opportunityId||i.opportunityId===selected.opportunityId||!i.opportunityId)).sort((a,b)=>b.date.localeCompare(a.date));
 const demo=s.companies.some(c=>c.demo);
 async function stageChange(id:string,from:string,to:string){if(from===to||busy||!isStage(to))return;setData(current=>current?.state?{...current,state:{...current.state,opportunities:current.state.opportunities.map(item=>item.id===id?{...item,stage:to}:item)}}:current);if(await send({action:'stage',id,stage:to,expectedStage:from})){setUndo({id,from,to});toast.success('Movida a '+to)}else void load()}
 async function convertLead(id:string){const saved=await send({action:'convertLead',id});if(!saved?.state)return;const lead=saved.state.leads.find((item:State['leads'][number])=>item.id===id);toast.success('Lead convertido. La empresa y la oportunidad conservan las notas');if(lead?.convertedCompanyId)setSelected({companyId:lead.convertedCompanyId,opportunityId:lead.convertedOpportunityId})}
 function table(headers:string[],rows:ReactNode[]){return rows.length?<Table><TableHeader><TableRow>{headers.map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows}</TableBody></Table>:<Blank filtered={!!query||companyFilter!=='all'||filter!=='all'}/>}
 return <SidebarProvider defaultOpen style={{"--sidebar-width":"248px","--sidebar-width-icon":"72px"} as React.CSSProperties}><Toaster position="bottom-right"/><Sidebar className="siarem-sidebar"><SidebarHeader><div className="brand">siarem<span>.</span></div><button className="workspace" onClick={()=>setTeam(true)}><span className="workspace-avatar">{data.tenant.slice(0,1).toUpperCase()}</span><span>{data.tenant}<small>Espacio compartido</small></span><ChevronRight size={14}/></button></SidebarHeader><SidebarContent><span className="nav-caption">ESPACIO COMERCIAL</span><SidebarMenu>{nav.map(n=><SidebarMenuItem key={n.name}><div className={view===n.name?"active-nav":""}><NavItem name={n.name} onClick={()=>changeView(n.name)}><n.icon size={18}/><span>{n.name}</span>{n.name==='Foco'&&critical+attention>0&&<span className="nav-count">{critical+attention}</span>}{n.name==='Leads'&&openLeads.length>0&&<span className="nav-count">{openLeads.length}</span>}</NavItem></div></SidebarMenuItem>)}</SidebarMenu></SidebarContent><SidebarFooter><button className="team-link" onClick={()=>setTeam(true)}><Users size={16}/><span>Mi equipo</span></button><div className="user-line"><span className="avatar">{data.user.slice(0,1).toUpperCase()}</span><span>{data.user}<small>{data.role==='owner'?'Propietario':'Miembro del equipo'}</small></span><a aria-label="Cerrar sesión" href="/signout-with-chatgpt?return_to=/" target="_top"><LogOut size={16}/></a></div></SidebarFooter></Sidebar><SidebarInset className="main-shell"><header className="topbar"><div><SidebarTrigger aria-label="Plegar o desplegar menú"/><span>Espacio comercial</span><ChevronRight size={13}/><strong>{view}</strong></div><span className="save-status"><span className="status-dot"/>{busy?'Guardando…':loading?'Actualizando…':'Guardado en el servidor'}</span></header><main className="content"><div className="page-heading"><div><div className="eyebrow">{new Intl.DateTimeFormat('es-ES',{weekday:'long',day:'numeric',month:'long',timeZone:'Europe/Madrid'}).format(new Date())}</div><h1>{pageCopy[view].title}</h1><p>{pageCopy[view].text}</p></div><button className="primary" onClick={()=>open(createKind(view))}><Plus size={16}/>{createLabel[createKind(view)]}</button></div>
 {error&&<div className="error-banner" role="alert"><span>{error}</span><button onClick={load}><RefreshCw size={14}/> Recargar datos</button></div>}
 {demo&&<div className="demo-banner"><span><span className="demo-tag">DEMOSTRACIÓN</span> Estás viendo datos marcados como demostración.</span><button onClick={()=>setDeletion({action:'deleteDemo'})}>Borrar demostración <Trash2 size={13}/></button></div>}
 {(view==='Foco'||view==='Leads'||view==='Facturas')&&<div className="metrics">{view==='Foco'&&<><button type="button" onClick={()=>changeView('Leads')}><span>Leads por trabajar</span><strong>{openLeads.length}<small>en bandeja</small></strong><span className="metric-note">{freshLeads} sin contactar · {readyLeads} listos para convertir</span></button><button type="button" onClick={()=>setFilter('all')}><span>Piden una acción</span><strong>{critical+attention}<small>oportunidades</small></strong><span className="metric-note"><b className="red">{critical} críticas</b> · {attention} con el cierre cerca</span></button><div><span>Importe en juego</span><strong>{eur(openOpps.reduce((a,o)=>a+o.amount,0))}</strong><span className="metric-note">{openOpps.length} oportunidades abiertas, sin ganadas ni perdidas</span></div></>}{view==='Leads'&&<><button type="button" onClick={()=>setFilter('Nuevo')}><span>Sin contactar</span><strong>{freshLeads}</strong><span className="metric-note">Aún no hay una conversación</span></button><button type="button" onClick={()=>setFilter('due')}><span>Acción vencida</span><strong className={dueLeads.length?'red':''}>{dueLeads.length}</strong><span className="metric-note">La fecha del siguiente paso ya pasó</span></button><button type="button" onClick={()=>setFilter('Cualificado')}><span>Listos para convertir</span><strong>{readyLeads}</strong><span className="metric-note">Pasan a empresa y oportunidad con sus notas</span></button></>}{view==='Facturas'&&<><div><span>Pendiente de cobro</span><strong>{eur(invoices.filter(i=>!i.paid).reduce((a,i)=>a+i.amount,0))}</strong><span className="metric-note">{invoices.filter(i=>!i.paid&&i.dueDate<today()).length} vencidas en esta vista</span></div><div><span>Cobrado</span><strong>{eur(invoices.filter(i=>i.paid).reduce((a,i)=>a+i.amount,0))}</strong><span className="metric-note">{invoices.filter(i=>i.paid).length} facturas cobradas</span></div><div><span>Facturado en la vista</span><strong>{eur(invoices.reduce((a,i)=>a+i.amount,0))}</strong><span className="metric-note">Suma de la lista filtrada</span></div></>}</div>}
 <section className={"working-surface surface-"+view}><div className="section-heading"><h2>{view==='Foco'?'Necesitan tu atención':view==='Leads'?'Bandeja de leads':view==='Pipeline'?'Oportunidades':view==='Ventas'?'Documentos comerciales':view==='Proyectos'?'Proyectos en marcha':view==='Empresas'?'Tus empresas':'Facturas y cobros'}<span className="count">{({Foco:focus.length,Leads:leads.length,Pipeline:opps.length,Empresas:companies.length,Ventas:(filter==='orders'?0:quotes.length)+(filter==='quotes'?0:orders.length),Proyectos:projects.length,Facturas:invoices.length} as any)[view]}</span></h2><a className="subtle" download href={"/api/export?"+new URLSearchParams({view,q:query,filter,company:companyFilter}).toString()}><Download size={14}/> Exportar CSV</a></div><div className="toolbar"><div className="search"><Search size={16}/><input aria-label="Buscar" placeholder={view==='Empresas'?'Buscar empresa, contacto o email…':view==='Leads'?'Buscar nombre, email o fuente…':'Buscar empresa u oportunidad…'} value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button onClick={()=>setQuery('')} aria-label="Limpiar búsqueda">×</button>}</div>{view!=='Empresas'&&view!=='Leads'&&<Pick label="Filtrar por empresa" value={companyFilter} onChange={setCompanyFilter} options={[{value:'all',label:'Todas las empresas'},...s.companies.map(c=>({value:c.id,label:c.name}))]}/>}<div className="filters">{(view==='Foco'?[['all','Con riesgo'],['2','Críticas'],['1','Atención'],['healthy','Al día']]:view==='Leads'?[['all','Todos'],['Nuevo','Nuevos'],['Contactado','Contactados'],['Cualificado','Cualificados'],['due','Vencidos'],['Convertido','Convertidos'],['Descartado','Descartados']]:view==='Ventas'?[['all','Todos'],['quotes','Presupuestos'],['orders','Pedidos']]:view==='Facturas'?[['all','Todas'],['pending','Pendientes'],['paid','Cobradas']]:[]).map(([v,l])=><button key={v} className={filter===v?'selected':''} onClick={()=>setFilter(v)}>{l}</button>)}</div></div>
 {view==='Leads'&&table(['LEAD','FUENTE','ESTADO','PRÓXIMA ACCIÓN',''],leads.map(l=><TableRow key={l.id} className="clickable" onClick={()=>open('leads',l)}><TableCell><span className="lead-name"><span className="lead-avatar">{l.name.slice(0,1).toUpperCase()}</span><span><strong>{l.name}</strong><small>{l.contact||l.email||'Sin contacto'}</small></span></span></TableCell><TableCell><span className="source-pill">{l.source}</span></TableCell><TableCell><Badge level={l.status==='Descartado'?2:l.status==='Convertido'?0:l.status==='Cualificado'?0:1}>{l.status}</Badge></TableCell><TableCell><span className={l.nextDate&&l.nextDate<today()&&l.status!=='Convertido'&&l.status!=='Descartado'?'red':''}>{l.nextDate||'Sin fecha'}</span><small>{l.notes||'Sin notas todavía'}</small></TableCell><TableCell><span className="row-actions">{l.status==='Convertido'&&l.convertedCompanyId?<button className="outline compact-action" onClick={e=>{e.stopPropagation();setSelected({companyId:l.convertedCompanyId!,opportunityId:l.convertedOpportunityId})}}>Ver oportunidad</button>:<button className="outline compact-action" disabled={busy||l.status==='Descartado'} onClick={e=>{e.stopPropagation();void convertLead(l.id)}}>Convertir en oportunidad</button>}{l.status!=='Convertido'&&actions('leads',l)}</span></TableCell></TableRow>))}
 {view==='Foco'&&table(['EMPRESA / OPORTUNIDAD','IMPORTE','ETAPA','ÚLTIMO CONTACTO','SIGUIENTE PASO','RIESGO'],focus.map(o=>{const r=risk(s,o);const task=s.followups.filter(t=>t.opportunityId===o.id&&!t.done).sort((a,b)=>a.dueDate.localeCompare(b.dueDate))[0];return <TableRow key={o.id} className="clickable" onClick={()=>setSelected({companyId:o.companyId,opportunityId:o.id})}><TableCell><button className="record-link" onClick={()=>setSelected({companyId:o.companyId,opportunityId:o.id})}><span className="company-icon">{company(o.companyId)?.name.slice(0,2).toUpperCase()}</span><span><strong>{company(o.companyId)?.name}</strong><small>{o.title}</small></span></button></TableCell><TableCell className="numeric">{eur(o.amount)}</TableCell><TableCell><span className="stage-label">{o.stage}</span></TableCell><TableCell><span>{!r.contacted?'Sin contacto':r.elapsed===0?'Hoy':`Hace ${r.elapsed} días`}</span><small>{!r.contacted?'Creada · ':''}{r.last}</small></TableCell><TableCell><span>{task?.title||o.nextStep||'Definir siguiente paso'}</span><small className={(task?.dueDate||o.nextDate)<today()?'red':''}>{task?.dueDate||o.nextDate||'Sin fecha'}</small></TableCell><TableCell><Badge level={r.level}>{r.label}</Badge><small className="risk-reason">{r.reason}</small></TableCell></TableRow>}))}
 {view==='Pipeline'&&<><PipelineBoard opportunities={opps} companyName={id=>company(id)?.name||'Sin empresa'} riskOf={id=>{const item=s.opportunities.find(opportunity=>opportunity.id===id);return item?risk(s,item).level:0}} busy={busy} onOpen={(companyId,opportunityId)=>setSelected({companyId,opportunityId})} onMove={(id,from,to)=>void stageChange(id,from,to)}/>{undo&&<div className="undo-bar">Movida a {undo.to}<button disabled={busy} onClick={async()=>{if(await send({action:'stage',id:undo.id,stage:undo.from,expectedStage:undo.to})){setUndo(null);toast.success('Movimiento deshecho')}}}>Deshacer</button></div>}</>}
 {view==='Empresas'&&table(['EMPRESA','CONTACTO','EMAIL / TELÉFONO','OPORTUNIDADES','SIN CONTACTO',''],companies.map(c=><TableRow key={c.id} className="clickable" onClick={()=>setSelected({companyId:c.id,opportunityId:s.opportunities.find(o=>o.companyId===c.id)?.id})}><TableCell><button className="record-link" onClick={()=>setSelected({companyId:c.id,opportunityId:s.opportunities.find(o=>o.companyId===c.id)?.id})}><span className="company-icon">{c.name.slice(0,2).toUpperCase()}</span><span><strong>{c.name}</strong>{c.demo&&<small>Demostración</small>}</span></button></TableCell><TableCell>{c.contact||'—'}</TableCell><TableCell>{c.email||'—'}<small>{c.phone}</small></TableCell><TableCell>{s.opportunities.filter(o=>o.companyId===c.id).length}</TableCell><TableCell>Alerta a los {c.contactDays} días</TableCell><TableCell>{actions('companies',c)}</TableCell></TableRow>))}
 {view==='Ventas'&&<>{filter!=='orders'&&<><h3 className="subheading">Presupuestos</h3>{table(['PRESUPUESTO','EMPRESA','IMPORTE','ESTADO',''],quotes.map(q=><TableRow key={q.id}><TableCell><strong>{q.title}</strong><small>{q.lines.map(l=>l.description).join(' · ')}</small></TableCell><TableCell>{company(s.opportunities.find(o=>o.id===q.opportunityId)?.companyId)?.name}</TableCell><TableCell className="numeric">{eur(total(q.lines))}</TableCell><TableCell>{s.orders.some(o=>o.quoteId===q.id&&o.confirmed)?<Badge level={0}>Confirmado</Badge>:<button className="outline" disabled={busy} onClick={async()=>{if(await send({action:'confirm',id:q.id}))toast.success('Pedido confirmado y proyecto creado')}}>Confirmar pedido <ArrowRight size={13}/></button>}</TableCell><TableCell>{!s.orders.some(o=>o.quoteId===q.id)&&<button className="subtle" onClick={()=>open('orders',{quoteId:q.id,title:q.title,lines:q.lines,confirmed:false})}>Crear pedido borrador</button>}{actions('quotes',q)}</TableCell></TableRow>))}</>}{filter!=='quotes'&&<><h3 className="subheading">Pedidos</h3>{table(['PEDIDO','EMPRESA','IMPORTE','ESTADO',''],orders.map(o=><TableRow key={o.id}><TableCell><strong>{o.title}</strong><small>{o.lines.map(l=>policyLabel[l.policy]).join(' · ')}</small></TableCell><TableCell>{company(companyForOrder(s,o.id))?.name}</TableCell><TableCell className="numeric">{eur(total(o.lines))}</TableCell><TableCell><Badge level={o.confirmed?0:1}>{o.confirmed?'Confirmado':'Borrador'}</Badge></TableCell><TableCell>{o.confirmed?<button className="outline" onClick={()=>open('invoice',{orderId:o.id,policy:o.lines[0].policy})}>Generar factura</button>:<><button className="outline" disabled={busy} onClick={()=>void send({action:'confirm',id:o.quoteId})}>Confirmar pedido</button><button className="subtle" onClick={()=>open('orders',o)}>Editar</button></>}<button className="subtle" onClick={()=>open('orders',o)}>Editar pedido</button><button className="icon-button" aria-label={'Eliminar pedido '+o.title} onClick={()=>askDelete('orders',o.id)}><Trash2 size={14}/></button></TableCell></TableRow>))}</>}</>}
 {view==='Proyectos'&&(projects.length?projects.map(p=>{const order=s.orders.find(o=>o.id===p.orderId)!;const tasks=s.delivery.filter(t=>t.projectId===p.id);const hrs=s.hours.filter(h=>tasks.some(t=>t.id===h.taskId));const cost=projectCost(s,p.id);return <article className="project" key={p.id}><div className="project-heading"><div><small>{company(companyForOrder(s,order.id))?.name} {p.demo?'· Demostración':''}</small><h3>{p.title}</h3></div><div className="project-numbers"><span>Pedido<strong>{eur(total(order.lines))}</strong></span><span>Coste de horas<strong>{eur(cost)}</strong></span><span className="margin">Margen<strong>{eur(total(order.lines)-cost)}</strong></span></div></div><div className="project-grid"><section><div className="section-heading"><h4>Tareas de entrega <small>{tasks.filter(t=>t.done).length}/{tasks.length}</small></h4><button className="subtle" onClick={()=>open('delivery',{projectId:p.id})}><Plus size={13}/> Tarea</button></div>{tasks.map(t=><div className="task-row" key={t.id}><Checkbox aria-label={'Completar '+t.title} checked={t.done} disabled={busy} onCheckedChange={()=>void send({action:'save',kind:'delivery',record:{...t,done:!t.done}})}/><span className={t.done?'done':''}>{t.title}<small>{order.lines[t.lineIndex].description}</small></span><button className="subtle" onClick={()=>open('hours',{taskId:t.id})}><Plus size={13}/> Horas</button>{actions('delivery',t)}</div>)}{!tasks.length&&<Blank/>}</section><section><div className="section-heading"><h4>Partes de horas</h4><span>{hrs.reduce((a,h)=>a+h.hours,0)} h</span></div>{hrs.map(h=><div className="hour-row" key={h.id}><Clock3 size={14}/><span>{tasks.find(t=>t.id===h.taskId)?.title}<small>{h.date} · {h.notes}</small></span><strong>{h.hours} h<small>{eur(h.hours*h.cost)}</small></strong>{actions('hours',h)}</div>)}{!hrs.length&&<p className="muted">Todavía no hay horas imputadas.</p>}</section></div><div className="project-footer"><span>Margen = pedido − coste de las horas imputadas</span><button className="subtle" onClick={()=>askDelete('projects',p.id)}>Eliminar proyecto</button></div></article>}):<Blank filtered={!!query||companyFilter!=='all'} text="Confirma un pedido en Ventas para crear su proyecto."/>)}
 {view==='Facturas'&&table(['FACTURA / EMPRESA','FECHA','VENCIMIENTO','IMPORTE','ESTADO',''],invoices.map(i=><TableRow key={i.id}><TableCell><strong>{i.title}</strong><small>{company(companyForOrder(s,i.orderId))?.name} · {policyLabel[i.policy]}</small></TableCell><TableCell>{i.date}</TableCell><TableCell className={!i.paid&&i.dueDate<today()?'red':''}>{i.dueDate}</TableCell><TableCell className="numeric">{eur(i.amount)}</TableCell><TableCell><Badge level={i.paid?0:1}>{i.paid?'Cobrada':'Pendiente'}</Badge>{i.paid&&<small>{s.payments.find(p=>p.invoiceId===i.id)?.date}</small>}</TableCell><TableCell>{!i.paid&&<button className="outline" onClick={()=>open('pay',{invoiceId:i.id,amount:i.amount})}>Registrar cobro</button>}{actions('invoices',i)}</TableCell></TableRow>))}
 </section>{view==='Foco'&&<div className="focus-foot"><span><Clock3 size={14}/> Aviso de cierre: 7 días · Sin contacto: según cada empresa</span><button onClick={()=>changeView('Pipeline')}>Ver todo el pipeline <ArrowRight size={14}/></button></div>}<footer className="app-footer"><span>SIAREM / ESPACIO COMERCIAL</span><span>Importes en EUR · Base de servicio, sin impuestos</span></footer></main></SidebarInset>
 <Sheet open={!!selected&&!!selectedCompany} onOpenChange={v=>{if(!v)setSelected(null)}}><SheetContent showCloseButton={false} className="detail-panel"><SheetClose className="close-panel" aria-label="Cerrar panel"><X size={17}/></SheetClose><SheetHeader><div className="eyebrow">EMPRESA{selectedCompany?.demo?' · DEMOSTRACIÓN':''}</div><SheetTitle>{selectedCompany?.name}</SheetTitle><SheetDescription>{selectedCompany?.contact||'Sin contacto principal'}{selectedCompany?.email?' · '+selectedCompany.email:''}</SheetDescription></SheetHeader><div className="panel-body"><div className="panel-actions"><button className="outline" onClick={()=>open('companies',selectedCompany)}>Editar empresa</button><button className="outline" onClick={()=>open('opportunities',{companyId:selectedCompany?.id})}><Plus size={14}/> Oportunidad</button></div><Pick label="Oportunidad del panel" value={selected?.opportunityId||''} options={[{value:'',label:'Todas las interacciones'},...s.opportunities.filter(o=>o.companyId===selected?.companyId).map(o=>({value:o.id,label:o.title}))]} onChange={v=>setSelected(x=>x?{...x,opportunityId:v}:null)}/>{selectedOpp&&<><div className="opportunity-detail"><h3>{selectedOpp.title}</h3><strong>{eur(selectedOpp.amount)}</strong>{actions('opportunities',selectedOpp)}<Pick label="Mover a" value={selectedOpp.stage} options={[...stages]} onChange={to=>void stageChange(selectedOpp.id,selectedOpp.stage,to)}/><Badge level={risk(s,selectedOpp).level}>{risk(s,selectedOpp).label}</Badge><p>{risk(s,selectedOpp).reason}</p><div className="next-step"><small>SIGUIENTE PASO</small><strong>{selectedOpp.nextStep||'Sin definir'}</strong><span>{selectedOpp.nextDate||'Sin fecha'}</span></div></div><div className="panel-actions"><button className="primary" onClick={()=>{const task=selectedTasks.find(t=>!t.done);setDraft(`Hola${selectedCompany?.contact?', '+selectedCompany.contact:''}:\n\nRetomo nuestra conversación sobre ${selectedOpp.title}. ${task?'El siguiente paso que tenemos pendiente es: '+task.title+'.':selectedOpp.nextStep?'Nos queda pendiente '+selectedOpp.nextStep+'.':'Me gustaría revisar contigo cómo avanzamos.'}\n\n¿Te encaja que lo revisemos esta semana?\n\nGracias.`)}}>Preparar seguimiento <ArrowUpRight size={14}/></button><button className="outline" onClick={()=>open('quotes',{opportunityId:selectedOpp.id,title:'Presupuesto · '+selectedOpp.title})}>Crear presupuesto</button></div></>}
 <div className="section-heading"><h3>Seguimientos</h3>{selectedOpp&&<button className="subtle" onClick={()=>open('followups')}><Plus size={14}/> Añadir tarea</button>}</div>{!selectedOpp&&<p className="muted">Selecciona una oportunidad para añadir seguimientos.</p>}{selectedTasks.map(t=><div className="task-row" key={t.id}><Checkbox aria-label={'Completar '+t.title} checked={t.done} disabled={busy} onCheckedChange={()=>void send({action:'complete',id:t.id})}/><span className={t.done?'done':''}>{t.title}<small className={!t.done&&t.dueDate<today()?'red':''}>{t.done?'Completada · ':''}{t.dueDate}</small></span>{actions('followups',t)}</div>)}{selectedOpp&&!selectedTasks.length&&<p className="muted">Sin tareas de seguimiento.</p>}
 <div className="section-heading"><h3>Histórico de contacto</h3><button className="subtle" onClick={()=>open('interactions')}><Plus size={14}/> Interacción</button></div><div className="timeline">{selectedInteractions.map(i=><article key={i.id}><div className="timeline-dot"/><header><strong>{i.kind}</strong><small>{i.date}</small>{actions('interactions',i)}</header><p>{i.notes}</p></article>)}</div>{!selectedInteractions.length&&<p className="muted">Todavía no hay interacciones.</p>}</div></SheetContent></Sheet>
 <Dialog open={draft!==null} onOpenChange={v=>{if(!v)setDraft(null)}}><DialogContent showCloseButton={false}><DialogClose className="close-panel" aria-label="Cerrar"><X size={17}/></DialogClose><DialogHeader><DialogTitle>Preparar seguimiento</DialogTitle><DialogDescription>Revisa el texto antes de copiarlo o abrir tu correo.</DialogDescription></DialogHeader><textarea className="followup-draft" aria-label="Texto del seguimiento" value={draft||''} onChange={e=>setDraft(e.target.value)}/><div className="panel-actions"><button className="primary" onClick={async()=>{try{await navigator.clipboard.writeText(draft||'');toast.success('Seguimiento copiado')}catch{toast.error('No se pudo copiar. Selecciona el texto y cópialo.')}}}>Copiar texto</button>{selectedCompany?.email&&<a className="outline" href={`mailto:${encodeURIComponent(selectedCompany.email)}?subject=${encodeURIComponent(selectedOpp?.title||'Seguimiento')}&body=${encodeURIComponent(draft||'')}`}>Abrir correo</a>}</div></DialogContent></Dialog>
 <Dialog open={team} onOpenChange={setTeam}><DialogContent showCloseButton={false}><DialogClose className="close-panel" aria-label="Cerrar"><X size={17}/></DialogClose><DialogHeader><DialogTitle>{data.tenant} · Equipo</DialogTitle><DialogDescription>Los compañeros que acepten tu invitación compartirán los datos de este espacio.</DialogDescription></DialogHeader><p>{data.user} · {data.role==='owner'?'Propietario':'Miembro'}</p>{data.role==='owner'&&<><button className="primary" disabled={busy} onClick={()=>void send({action:'invite'})}>Crear invitación</button>{invite&&<><Field label="Código de un solo uso · válido durante 24 horas"><input readOnly value={invite}/></Field><button className="outline" onClick={async()=>{try{await navigator.clipboard.writeText(invite);toast.success('Invitación copiada')}catch{toast.error('Copia el código manualmente')}}}>Copiar código</button></>}</>}</DialogContent></Dialog>
 <AlertDialog open={!!deletion} onOpenChange={v=>{if(!v)setDeletion(null)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{deletion?.action==='deleteDemo'?'Borrar todos los datos de demostración':'Eliminar registro'}</AlertDialogTitle><AlertDialogDescription>{deletion?.action==='deleteDemo'?'Se eliminarán las empresas, oportunidades y documentos marcados como demostración. Tus datos propios se conservarán.':deletion?.kind==='invoices'?'Se eliminarán la factura y su cobro, si lo tiene. Las horas volverán a estar disponibles para facturar.':'Esta acción no se puede deshacer. Si hay documentos vinculados, tendrás que eliminarlos primero.'}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><button className="danger" disabled={busy} onClick={async()=>{if(deletion&&await send(deletion)){setDeletion(null);toast.success('Datos eliminados')}}}>Eliminar</button></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <Dialog open={!!form} onOpenChange={v=>{if(!v)setForm(null)}}><DialogContent showCloseButton={false} className="form-dialog"><DialogClose className="close-panel" aria-label="Cerrar formulario"><X size={17}/></DialogClose><DialogHeader><DialogTitle>{form?.kind==='pay'?'Registrar cobro':form?.kind==='invoice'?'Generar factura':`Guardar ${labels[form?.kind||'companies']}`}</DialogTitle><DialogDescription>Los campos se guardan en el espacio de {data.tenant}.</DialogDescription></DialogHeader>{form&&<RecordForm key={form.record.id} form={form} state={s} busy={busy} error={formError} refresh={load} onSubmit={async(record:any)=>{let cmd:any={action:'save',kind:form.kind,record};if(form.kind==='invoice')cmd={...record,action:'invoice',id:record.orderId};if(form.kind==='editInvoice')cmd={...record,action:'editInvoice'};if(form.kind==='pay')cmd={action:'pay',id:record.invoiceId,date:record.date};if(await send(cmd)){setForm(null);toast.success('Guardado')}}}/>}</DialogContent></Dialog>
 </SidebarProvider>
}
function RecordForm({form,state:s,busy,error,refresh,onSubmit}:{form:Form;state:State;busy:boolean;error:string;refresh:()=>void;onSubmit:(r:any)=>Promise<void>}){
 const [r,setR]=useState<any>(form.record);const k=form.kind;
 const set=(key:string,v:any)=>setR((old:any)=>({...old,[key]:v}));
 const input=(key:string,label:string,type='text',props:any={})=><Field label={label}><input type={type} value={r[key]??''} onChange={e=>set(key,type==='number'?(e.target.value===''?'':Number(e.target.value)):e.target.value)} onInput={e=>{if(type==='date')set(key,e.currentTarget.value)}} {...props}/></Field>;
 const pick=(key:string,label:string,options:any[])=><Field label={label}><Pick value={String(r[key]??'')} onChange={v=>set(key,key==='lineIndex'?Number(v):v)} label={label} options={options}/></Field>;
 const oppOptions=[{value:'',label:'Selecciona una oportunidad'},...s.opportunities.map(o=>({value:o.id,label:`${s.companies.find(c=>c.id===o.companyId)?.name} · ${o.title}`}))];
 const taskOptions=[{value:'',label:'Selecciona una tarea'},...s.delivery.map(t=>({value:t.id,label:`${s.projects.find(p=>p.id===t.projectId)?.title} · ${t.title}`}))];
 const order=s.orders.find(o=>o.id===r.orderId);
 const invoiced=(policy:string)=>s.invoices.filter(i=>i.orderId===order?.id&&i.policy===policy).reduce((a,i)=>a+i.amount,0);
 const eligibleHours=s.hours.filter(h=>{const t=s.delivery.find(t=>t.id===h.taskId);const p=s.projects.find(p=>p.id===t?.projectId);return p?.orderId===order?.id&&order?.lines[t?.lineIndex??-1]?.policy==='hours'&&!s.invoices.some(i=>i.hourIds.includes(h.id))});
 return <form className="record-form" noValidate onSubmit={e=>{e.preventDefault();void onSubmit(r)}}>
 {k==='leads'&&<>{input('name','Empresa o contacto *')}{input('contact','Persona de contacto')}{input('email','Email','email')}{input('phone','Teléfono','tel')}{pick('source','Origen',[...leadSources])}{pick('status','Estado',leadStatuses.filter(status=>status!=='Convertido'||r.status==='Convertido'))}{input('nextDate','Fecha de la próxima acción','date')}<Field label="Qué sabemos"><textarea value={r.notes} onChange={e=>set('notes',e.target.value)} placeholder="Interés, contexto y por qué merece seguimiento"/></Field>{r.status==='Convertido'&&<p className="muted">Este lead ya es una oportunidad. El historial se conserva en la empresa.</p>}</>}
 {k==='companies'&&<>{input('name','Nombre de la empresa *')}{input('contact','Persona de contacto')}{input('email','Email','email')}{input('phone','Teléfono','tel')}{input('contactDays','Días sin contacto para marcar riesgo *','number',{min:1,max:90})}</>}
 {k==='opportunities'&&<>{pick('companyId','Empresa *',[{value:'',label:'Selecciona una empresa'},...s.companies.map(c=>({value:c.id,label:c.name}))])}{input('title','Nombre de la oportunidad *')}{input('amount','Importe estimado (€) *','number',{min:0,step:.01})}{pick('stage','Etapa',[...stages])}{input('closeDate','Fecha de cierre *','date')}{input('nextStep','Siguiente paso')}{input('nextDate','Fecha del siguiente paso','date')}</>}
 {k==='interactions'&&<>{pick('kind','Tipo de contacto',['Llamada','Email','Reunión','Nota'])}{input('date','Fecha *','date')}<Field label="Qué habéis hablado *"><textarea value={r.notes} onChange={e=>set('notes',e.target.value)} autoFocus/></Field></>}
 {k==='followups'&&<>{pick('opportunityId','Oportunidad *',oppOptions)}{input('title','Qué hay que hacer *')}{input('dueDate','Fecha de seguimiento *','date')}</>}
 {(k==='quotes'||k==='orders')&&<>{k==='quotes'?pick('opportunityId','Oportunidad *',oppOptions):pick('quoteId','Presupuesto de origen *',s.quotes.map(q=>({value:q.id,label:q.title})))}{input('title','Nombre del documento *')}<h3>Líneas de servicio</h3>{r.confirmed&&<p className="muted">Pedido confirmado: puedes cambiar su nombre. Sus líneas se conservan para mantener la trazabilidad.</p>}{r.lines.map((l:any,i:number)=>{const patch=(key:string,value:any)=>set('lines',r.lines.map((x:any,n:number)=>n===i?{...x,[key]:value}:x));return <fieldset className="service-line" key={i} disabled={r.confirmed}><legend>Servicio {i+1}</legend><Field label="Descripción del servicio *"><input value={l.description} onChange={e=>patch('description',e.target.value)}/></Field><div className="form-grid"><Field label={l.policy==='hours'?'Horas previstas *':'Cantidad *'}><input type="number" min="0.01" step="0.01" value={l.quantity} onChange={e=>patch('quantity',Number(e.target.value))}/></Field><Field label={l.policy==='hours'?'Precio por hora (€) *':'Precio unitario (€) *'}><input type="number" min="0" step="0.01" value={l.price} onChange={e=>patch('price',Number(e.target.value))}/></Field></div><Field label="Política de facturación"><Pick value={l.policy} onChange={v=>patch('policy',v)} label="Política de facturación" options={Object.entries(policyLabel).map(([value,label])=>({value,label}))}/></Field><Field label="Tareas del proyecto · una por línea *"><textarea value={l.tasks} onChange={e=>patch('tasks',e.target.value)}/></Field>{r.lines.length>1&&<button type="button" className="subtle red" onClick={()=>set('lines',r.lines.filter((_:any,n:number)=>n!==i))}>Quitar servicio</button>}</fieldset>})}<button disabled={r.confirmed} type="button" className="outline" onClick={()=>set('lines',[...r.lines,{description:'',quantity:1,price:0,policy:'fixed',tasks:'Entrega y revisión'}])}><Plus size={14}/> Añadir línea</button><div className="form-total">Total del documento <strong>{eur(total(r.lines))}</strong></div></>}
 {k==='delivery'&&<>{pick('projectId','Proyecto *',s.projects.map(p=>({value:p.id,label:p.title})))}{input('title','Tarea de entrega *')}{pick('lineIndex','Servicio del pedido *',(s.orders.find(o=>o.id===s.projects.find(p=>p.id===r.projectId)?.orderId)?.lines||[]).map((l,i)=>({value:String(i),label:l.description})))}</>}
 {k==='hours'&&<>{pick('taskId','Tarea del proyecto *',taskOptions)}{input('date','Fecha *','date')}{input('hours','Horas imputadas *','number',{min:.01,max:24,step:.25})}{input('cost','Coste interno por hora (€) *','number',{min:0,step:.01})}{input('notes','Trabajo realizado')}<p className="muted">Coste imputado: {eur((Number(r.hours)||0)*(Number(r.cost)||0))}</p></>}
 {(k==='invoice'||k==='editInvoice')&&<>{k==='invoice'&&<><Field label="Pedido confirmado *"><Pick value={r.orderId} onChange={v=>{const o=s.orders.find(o=>o.id===v);setR({...r,orderId:v,policy:o?.lines[0].policy||'fixed',hourIds:[]})}} label="Pedido confirmado" options={[{value:'',label:'Selecciona un pedido'},...s.orders.filter(o=>o.confirmed).map(o=>({value:o.id,label:o.title}))]}/></Field>{pick('policy','Política de facturación',Array.from(new Set(order?.lines.map(l=>l.policy)||[])).map(value=>({value,label:policyLabel[value]})))}</>}{input('title','Número o referencia de factura *')}{input('date','Fecha de emisión *','date')}{input('dueDate','Fecha de vencimiento *','date')}{k==='invoice'&&r.policy==='milestones'&&input('amount','Importe del hito (€) *','number',{min:.01,step:.01})}{k==='invoice'&&r.policy!=='hours'&&<p className="form-total">Pendiente de facturar <strong>{eur(total(order?.lines.filter(l=>l.policy===r.policy)||[])-invoiced(r.policy))}</strong></p>}{k==='invoice'&&r.policy==='hours'&&<><h3>Horas pendientes de facturar</h3>{eligibleHours.map(h=><label className="task-row" key={h.id}><Checkbox checked={r.hourIds.includes(h.id)} onCheckedChange={checked=>set('hourIds',checked?[...r.hourIds,h.id]:r.hourIds.filter((id:string)=>id!==h.id))}/><span>{s.delivery.find(t=>t.id===h.taskId)?.title}<small>{h.date} · {h.hours} h</small></span></label>)}{!eligibleHours.length&&<p className="muted">No hay horas pendientes para este pedido.</p>}</>}</>}
 {k==='pay'&&<><p className="form-total">Cobro completo <strong>{eur(r.amount)}</strong></p>{input('date','Fecha del cobro *','date')}</>}
 {error&&<div className="error" role="alert">{error}<button type="button" className="subtle" onClick={refresh}>Recargar datos conservando el formulario</button></div>}<button className="primary save-button" disabled={busy}>{busy?'Guardando…':k==='invoice'?'Generar factura':k==='pay'?'Registrar cobro':'Guardar'}</button>
 </form>
}
